### ISSUE TITLE
enhance getFieldInfo() to get id as well as names

### ISSUE THREAD

**Issue by offer-shmuely** [EdgeTX/edgetx#1285]
I like to write a new gauge widget
something like this:

![image](https://user-images.githubusercontent.com/7026911/147117545-800e8be2-3ea6-49ac-8b59-a926b0494e3a.png)

we need  a way to read a source parameter in widget options (supplied by the user)
 and display it's info

I declare the following for user input:
```
local options = {
     {  "Source1", SOURCE, 123 }    -- RSSI
}
```

to use it:
```
// source1 is a number
fieldNameAsInt = wgt.options.Source1

// this one can not work
fieldinfo = getFieldInfo(fieldNameAsInt)
```

I love to have one of the two:
**option 1**
support int as well 
`getFieldInfo(fieldName**AsInt**) or getFieldInfo**2**(fieldNameAsInt)
`
**option2** 

implement new function
`fieldNameAsString = fieldIdToFieldName(fieldNameAsInt)`

**Comment by offer-shmuely** [comment]
adding sample file

```
local options = {
  { "Source", SOURCE, 251 } -- RSSI
}

local function create(zone, options)
  local wgt = { zone = zone, options = options }
  return wgt
end

local function update(wgt, options)
  if (wgt == nil) then return end
  wgt.options = options
end

function refresh(wgt)
  if (wgt == nil) then return end

  print("wgt.source: " .. wgt.options.Source)

  -- can work with name or id
  local fieldValue = getValue(wgt.options.Source)
  print("fieldValue: " .. fieldValue)

  -- can work with name, can NOT work with id
  local fieldinfo = getFieldInfo(wgt.options.Source)
  if fieldinfo == nil then
    print("error, field-info NOT available")
    return
  end

  print("fieldinfo.id: " .. fieldinfo.id)


end

return { name = "fieldInfo0", options = options, create = create, update = update, refresh = refresh }

```

**Comment by jfrickmann** [comment]
`getFieldInfo` uses tables with source names that are generated by a Python script during the build. These are similar but not the same as the names that you see on the screen when you pick a source for something:
![Untitled](https://user-images.githubusercontent.com/16344987/147273940-cd4b5b62-f845-4524-b714-a8299c2a0d8b.png)
In #1154, I have made functions for getting switch positions, and instead of creating my own names, I have used the exact same names that you see on the screen. The advantage of this approach is that it is much simpler to implement, as I use the existing functions, and that you get 1:1 between Lua and the screen.
One problem with this approach is that the names on the screen contain special characters. I have solved that by also providing string constants for the special characters in #1169.
In #1154, I have provided functions to get the name from an index, get the index from a name, and get a value from the index.
So if you are interested, I can use the same approach to create the following functions for sources:
- `getSourceIndex(name)` is similar to `getFieldInfo(name).id`, except that we are using the name that you see on the screen (with special chars) instead of the names in [this table](https://downloads.open-tx.org/2.3/release/firmware/lua_fields_x12s.txt).
- `getSourceName(index)` will get you the name that you see on the screen, and I believe that it would work with index values from the above function as well as `getFieldInfo(name).id`, as these _should_ be the same.
- I _think_ that `getValue(index)` would work with all of the indices, so _probably_ no need to change anything here.

Please let me know what you think about that.

**Comment by offer-shmuely** [comment]
I will love to get the `getSourceName(index) `
then I can continue with my small project

**Comment by jfrickmann** [comment]
After our discussion on Discord, I was planning to modify `getFieldInfo` so it can also search for an id like `getValue`. Is that still OK?
Since it is Xmas now, it will probably take a few days before I have time to do it.

**Comment by offer-shmuely** [comment]
yep, that will be great as well!

**Comment by jfrickmann** [comment]
Please see #1300

**Comment by jfrickmann** [comment]
OK, GitHub is working again, and all checks have passed. So there is FW to test!
