### ISSUE TITLE
Taranis X9D Battery Bay Serial Port VBAT Not Software Controlled

### ISSUE THREAD

**Issue by techfixpros** [EdgeTX/edgetx#1365]
B01 X9D Taranis w/ETx 2.5.0

On OTx, selecting OFF in Hardware -> Serial Port turns off the VBAT output. ETx 2.5.0 provides VBAT output regardless what this is set to.
Without being able to turn off the VBAT, the external BT module has to be unplugged to turn it off, and the cables have to be routed outside of the transmitter case.

Reference: https://github.com/opentx/opentx/wiki/Taranis-IO-ports

**Comment by raphaelcoeffic** [comment]
This will be tackled as part of #1089.

**Comment by pfeerick** [comment]
It would appear from this video (running OTX 2.3.7), that the power to VMAIN (the power connector on the serial port) is not actually software switched on the X9D... perhaps this is a mistake on the wiki since it is exactly the same wording as used to describe the module bay BATT pin, which is software controlled?) 

Earlier in the video he describes how he makes up the connector, and wires a regulator up to drop the voltage for the bluetooth module, but at this point he has the bluetooth module running, yet the serial port is still set to off, and is about to go into the settings and change it to telem mirror. 
https://youtu.be/DY8W6bd7UQk?t=846
