### ISSUE TITLE
Crossfire doesn't connect with onebit enabled and model's receiver number different from 00

### ISSUE THREAD

**Issue by Lanzo98** [EdgeTX/edgetx#1436]
**Describe the bug**
Crossfire doesn't connect with onebit enabled and model's receiver number different from 00. Both telemetry and connection is lost 

**To Reproduce**
Enable one bit mode
Change model's receiver number, different from 00

**Expected behavior**
Telemetry and connection between Rx and TX works

**General information**
 - EdgeTX version 2.5.0
 - Hardware Frsky X9D

**Comment by raphaelcoeffic** [comment]
Is this the good old bug with the Receivers that used to ignore the receiver number but don't now? Have you tried to rebind with a receiver number set?

**Comment by Lanzo98** [comment]
Honestly I don't even know the meaning of the receiver number, haven't tried to rebind, I simply putted 00

**Comment by pfeerick** [comment]
Receiver number is so that you can make it so that only the right model setup will control a given model. i.e. instead of all your receivers operating regardless of the model you have selected in the transmitter, receivers will only work if you have the same id number assigned on both sides. Or if it is 0, it is supposed to be ignored. Maybe.

**Comment by Lanzo98** [comment]
Yes, the strange thing is that on Open tx the model was saved and binded with receiver number 02, but when I putted the models on Open tx it didn't connect to the Rx. But with 00 works

**Comment by gagarinlg** [comment]
is still still an issue?
