### ISSUE TITLE
Edge TX Companion 2.6.

### ISSUE THREAD

**Issue by Wingy1690** [EdgeTX/edgetx#1459]
When I open a airplane file in Companion 2.6 I get the following message. 
![Screenshot 2022-01-16 191746](https://user-images.githubusercontent.com/90584553/149704465-8c09195b-aa9e-4f54-bcb6-7e89ff5b632f.png)
![Screenshot 2022-01-16 191746](https://user-images.githubusercontent.com/90584553/149704507-d29c4605-33a2-4cfd-a54f-f6e41738e2cd.png)
I did not get this in 2.5
Any Ideas??

**Comment by pfeerick** [comment]
Can you attach one of the offending files? (change the file extension to `.zip` so github will accept it). And is this with 2.6.0-RC3?

**Comment by pfeerick** [comment]
@Wingy1690 Really need those files if you want any resolution to this ;)

**Comment by ParkerEde** [comment]
I got the same error message. 
Horus X10 EXPRESS: 
If i convert the otx bin files (SD Card as datasource) with the standalone simulator, copy the created yml to the etx archiv and open it in companion. Only D16 is affected.

**Comment by pds59** [comment]
radiomaster t16 s same problem with companion 2.6 , if this can help in my case, solved by loading old  b. up. otx file

**Comment by pfeerick** [comment]
I'm going to assume since there was no further commentary or files uploaded this issue is gone. Please open a new issue and also provide a reproudcable test case - i.e. a zip of the radio/models folders from the radio, or the OTX/ETX file that triggers this, with `.zip` as the extension so github accepts it.
