### ISSUE TITLE
ETX 2.6 Companion + Zorro: message 'File board ... does not match current profile board'

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#1541]
When transferring models from Zorro transmitter into ETX Companion 2.6 I get an error message, I think it's spurious.

To reproduce:

1. Connect to Companion via USB
2. Menu 'Read Models and Settings from Radio'
3. Then I get this message

![2022-02-01_223521](https://user-images.githubusercontent.com/6317479/152063576-bdb0cd8c-cafa-4c79-b1b2-14fcb85237bd.png)

After dismissing the message, the models are transferred as expected.

Screenshot of Companion settings:
![2022-02-01_223550](https://user-images.githubusercontent.com/6317479/152063914-164c59b1-1cd0-4308-9576-18779569a8cc.png)

**Comment by elecpower** [comment]
That is a bug. Will need to check whether the issue is on radio or Companion side

**Comment by pfeerick** [comment]
I can't reproduce this - when importing from zorro it is fine. Since it says "file board", can you share your `RADIO/radio.yml` file?

**Comment by RC-SOAR** [comment]
Sure, radio.yml file attached. Thanks for looking at this.

[radio - yml.txt](https://github.com/EdgeTX/edgetx/files/7982679/radio.-.yml.txt)

**Comment by elecpower** [comment]
The radio.yml file is missing the board entry and for historical reasons it assumes TX16S when it should say "unknown"

**Comment by pfeerick** [comment]
Ok, so the error is coming up because the `board:` entry is missing completely... i.e. usually within the first three lines (it can move around a bit) you'll have `board: zorro` which is what Companion is looking for to work out which radio config it's reading... so given this seems to be stemming from #1542, there are probably two bugs present... 
1) when `board` entry is missing, Companion assumes TX16s rather than saying... Unknown?
2) the board entry isn't being written when trying to convert by switching the profile

**Comment by elecpower** [comment]
2. The code always writes the current profile firmware board to the radio.yml file.
