### ISSUE TITLE
[NV14] problem with external module update (ExpressLRS - R9M)

### ISSUE THREAD

**Issue by nightflasher** [EdgeTX/edgetx#1584]
i've switched over to edgeTX today and wanted to update the R9M module with latest and greatest ExpressLRS 2.2.0 - but there was this "no sync" error message and the module can't be updated.

**Comment by yhomega** [comment]
I used a st link. Wasted too much time trying with opentx and nv14. Seems with edge tx it doesnt work too

**Comment by nightflasher** [comment]
@yhomega this is not correct, it worked fine with the latest version of openTX by qba667 and stefan73.

**Comment by stefan73** [comment]
Yes, it works fine on the OpenFlySky branch. I guess the reason is that the ext module driver is vastly incomplete.

Look at src/targets/nv14/extmodule_helper.cpp
And compare this to https://github.com/open-flysky/Flysky-OpenTX-Test-Branch/blob/pulses23/radio/src/targets/nv14/extmodule_driver.cpp

This looks mergable to me.

**Comment by raphaelcoeffic** [comment]
@stefan73 do you want to give it a shot? (PR?) You should know however that the external module driver has been completely re-written for horus & taranis target family, so that you might have to implement a completely different interface now. Also it should be converted to HAL/LL. Let me know if you need guidance.

**Comment by raphaelcoeffic** [comment]
Guys, would you mind to retest this on the latest nightly? The complete module code has been rewritten and tested quite a fair bit. At least on EL18 this work quite good for me.

**Comment by raphaelcoeffic** [comment]
@pfeerick should we close this one? (no feedback since Feb, and it seems to work for us)

**Comment by gagarinlg** [comment]
Seems to work OK for us, so it is closed.
If someone still has this problem, please comment.
