### ISSUE TITLE
When the [SYS Menu] adjusts the backlight, the string is not truncated correctly.

### ISSUE THREAD

**Issue by hmjack2008** [EdgeTX/edgetx#1795]
**Radiomaster TX16S**

- In Chinese translations (CN & TW), adjusting the [Backlight/Mode] on the [SYS Menu] page, the string was not truncated correctly.
![screen_TX16S_cn_Fail](https://user-images.githubusercontent.com/3375423/161414290-7661a424-6e72-41aa-87b1-7e157431c21a.jpg)

- The English (EN) is correct.
![screen_TX16S_en_OK](https://user-images.githubusercontent.com/3375423/161414295-9ad91972-877d-4158-a081-931f5ab949ae.jpg)

- I tried adding a string terminator ('\0') and it displays correctly.
![screen_TX16S_tw_OK](https://user-images.githubusercontent.com/3375423/161414298-d3e315c7-546e-4730-82db-700caca4b484.jpg)

**\radio\src\translations\tw.h.txt**
#define LEN_VBLMODE    "\005"
#define TR_VBLMODE    "關閉\0" "按鍵\0" "操控\0" "全部\0" "開啟\0"

**General information**
 - EdgeTX version (TW and CN, 2.6 and nightly)
 - Hardware (TX16S)

**Comment by pfeerick** [comment]
Thanks for catching that. The actual fault was in how the entries for that menu were being filtered so that "OFF" isn't shown on colorlcd... compiling the linked PR is back to showing only two characters for TW... does this look right to you?

![image](https://user-images.githubusercontent.com/5500713/161422517-d4768d3b-0666-437c-8307-075a711127e3.png)

![image](https://user-images.githubusercontent.com/5500713/161422562-40d6d1c7-5c0c-4fae-909b-1fd599d992d5.png)

**Comment by hmjack2008** [comment]
Yes, that's what I need.
Thanks for the help!
