### ISSUE TITLE
Faulty Inputs names syncronization Companion -> Radio

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#1807]
![screen-2022-04-05-085907](https://user-images.githubusercontent.com/46420768/161718010-a66aae1e-61c0-44ff-ab94-4c13132abc54.png)

That's what I got on radio after writing settings on Companion :)
Unfortunately spotted to late to catch exact moment.
But to check if everyhing ok in code with sync when Custom ihardware inputs names are set

**General information**
 - EdgeTX version 2.6.0 release
 - Hardware RM TX16S

**Comment by pfeerick** [comment]
This is not companion related... and I'm not sure it's actually 2.6 related... I think you're running 2.7-rc1, as this is a fixed bug that was introduced just before RC1 AFAIK... 

I rasied it in https://github.com/EdgeTX/edgetx/pull/1754, and it was fixed in https://github.com/EdgeTX/edgetx/pull/1770
