### ISSUE TITLE
X9D+ (2015) switch position text missing

### ISSUE THREAD

**Issue by jj-uk** [EdgeTX/edgetx#1855]
The switch designators, e.g. SA !SA, SB, etc including the stick names are missing throughout the firmware.

See images below.

**To Reproduce**

**Expected behavior**
Switch and stick names should be displayed.

**Screenshots**

![20220418_231337](https://user-images.githubusercontent.com/10943625/163886661-597fa686-4cf0-4be1-8f76-4f8d2af1f3ff.jpg)
![20220418_231344](https://user-images.githubusercontent.com/10943625/163886672-be770000-3838-4f9c-86b6-b52890e3186c.jpg)
![20220418_231356](https://user-images.githubusercontent.com/10943625/163886685-85a8c936-f3ce-44ba-8d60-0422fe486e0e.jpg)
![20220418_231403](https://user-images.githubusercontent.com/10943625/163886697-2f3bcf62-8e76-44d5-a314-aec57d2c1a5b.jpg)
![20220418_231426](https://user-images.githubusercontent.com/10943625/163886705-4e08599a-4dde-47ff-be3e-0de78b8f1dcf.jpg)
![20220418_231446](https://user-images.githubusercontent.com/10943625/163886709-379766f8-81c3-4e3b-b20f-fa8cdfd897b0.jpg)
![20220418_231500](https://user-images.githubusercontent.com/10943625/163886716-acfbcc4d-220f-4160-adca-3308d37d09aa.jpg)
![20220418_231516](https://user-images.githubusercontent.com/10943625/163886720-6566788f-8fe7-48a2-859b-7cf035940bb7.jpg)

**General information**

Taken from version screen in radio:
 - FW: edgetx-9xd+
 - VERS: 2.7.0 (f79978b6)
 - DATE: 2022-04-16 03:41:02
 - CFGV: 221
 
- Hardware Frsky X9D+ 2015

**Comment by pfeerick** [comment]
Can you also upload at least your `RADIO\radio.yml` - better still if you can do both MODELS and RADIO folders... as I suspect there is something wrong in the formatting of the config file as I'm not seeing this on the X9D+2019 - which as far as the UI code is concerned should be exactly the same.

**Comment by jj-uk** [comment]
No problem. Find attached. 
I tried to change the splash screen timeout in companion, then write the models back to the radio. That didn't change the timeout value in the radio. It seems that the splash screen timeout isn't saved in the radio yaml file. Not sure if me doing that broke the file?

[Models and Radio.zip](https://github.com/EdgeTX/edgetx/files/8508655/Models.and.Radio.zip)

**Comment by pfeerick** [comment]
Ok, so the reason your switch names are "missing" is because they have been defined as blank - three SPACES:
![image](https://user-images.githubusercontent.com/5500713/163894563-a1773345-aa56-4c73-825a-fa0735b298e3.png)

Same for the sticks, pots and sliders... 

To fix that, simply remove the spaces between the "" - and radio will use the default rather than "custom" name. I've just done a find and replace if you want to drop this radio.yml back on the radio (after unzipping)...
[radio.zip](https://github.com/EdgeTX/edgetx/files/8508734/radio.zip)

For power delay (pwrOnSpeed, pwrOffSpeed), they are both 0, which means two seconds (default 2 seconds - value chosen) ... you can change that to `-1` if you want the maximum 3 second delay, or 1 or 2 to reduce the power delay to 1 or 0 seconds respectively... if the radio isn't correctly updating them, that is.

**Comment by jj-uk** [comment]
Thanks. I didn't make those changes to the text, so there must be a bug somewhere that's caused it. I'll try to reproduce the problem and report back.
