### ISSUE TITLE
Unable to set packet rate to 500 using lua script for betafpv elrs nano tx module

### ISSUE THREAD

**Issue by asudhir1947** [EdgeTX/edgetx#1935]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Other (Please specify below)

### Current Behavior

Upgraded to EdgeTX 2.7 from 2.5

1. Launch ELRS LUA
2. Packet while on 2.5 was set to 500, now packet rate is automatically on 250
3. Attempt to change packet rate to 500, can see the number increment to 500, but pressing OK changes it to back to 250, unable to get 500 to stick

### Expected Behavior

1. Packet rate can be set to 500

### Steps To Reproduce

1. Launch ELRS LUA
2. Attempt to change packet rate to 500, can see the 500 packet rate, but cannot get it to stick after pressing ok

### Version

2.7.0

### Transmitter

FrSky X-Lite / S / Pro

### Anything else?

This feature works properly on 2.5. I cannot change the baud rate to > 400k as I get telemetry lost/recovered warning (even though there is no telemetry loss) and it continues on forever, more an annoyance than an actual issue. This has been discussed quite a bit on the Facebook ELRS group and is a known issue/annoyance and the only way to avoid it is to set baud rate to 400k

**Comment by pfeerick** [comment]
> the only way to avoid it is to set baud rate to 400k

If the baud rate is lower than 400k, setting it to a minimum of 400k is the correct and appropriate fix. ELRS **cannot** operate above 250Hz with a lower than 400k baud rate, and newer ELRS Lua scripts will tell you that if you try to set the packet rate higher than that the serial baud rate can accommodate. So while you might be able to scroll to 500 or F1000, when you try to actually apply it, the Lua will do the checks and reject your selection if it is not valid. 

So the real question here now is one of "is there really an issue here" still. You _probably_ can't go above 400k due to slow  inverters. I presume you have tried enabling the OneBit sample mode in SYS/Hardware... _maybe_ you can sneak up to 921k then... (or at least should have better 400k stability)... it will probably be very hardware and maybe even temperature dependent how well that works above 400k. Otherwise, I think we are going to have to close this as a "hardware requires modification to resolve" issue as I don't think there is anything further we can do on the software side. 

![image](https://github.com/EdgeTX/edgetx/assets/5500713/58f45976-13fc-4322-bd16-95e3680405ff)
