### ISSUE TITLE
Edge Tx 2.7.0 Gives single status Error

### ISSUE THREAD

**Issue by MartinHugh** [EdgeTX/edgetx#2129]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Using
Radiomaster TX16S  (Edge Tx 2.7.0)
HappyModel ES24TX 2400 TX with ELRS 2.2
HappyModel ES24TX 2400 TX with ELRS 2.5

If I turn the radio on with an ELRS model selected, I get a 
Status "500 Hz 1 Err"
indicated on the Model Setup page, with **either** module fitted,

I am not experiencing any control issues that I know of, but am concerned something is not as it should be.
The count does not appear to go above 1, so this seems a different problem to https://github.com/EdgeTX/edgetx/issues/2091

### Expected Behavior

I would expect the status line to show

Status "500 Hz 0 Err"

### Steps To Reproduce

Turn on radio with ELRS model selected
Go to Model Setup page
Scroll into the External RF block
Locate the Status metric

### Version

2.7.0

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
There will always be a one or two errors due to how the module responds from power up (i.e. whether it initially responds at the baud rate set or has to run auto-baud tuning). You'll also get one or two errors when you change the serial baud rate, etc. I think any change to this will be cosmetic at best, and downright misleading at worst. As a comparison, the RM TX16S and Jumper T-Lite that I have (which both have internal ELRS modules) will show 0 errs right from power up. Whereas my HM ES24TX module always has one error. 

This is not a bug, but something that you need to know is *normal* and *expected*.
