### ISSUE TITLE
some danish translations are to long for 128x64 pixel CLDs

### ISSUE THREAD

**Issue by gagarinlg** [EdgeTX/edgetx#2294]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

some option names on the "radio setup" and "hardware" pages are longer than the available space.

### Expected Behavior

the texts for the smaller LCDs should be shortened to fit into the available space

### Steps To Reproduce

ise simu/simulator/radio with a small screen and check all pages

### Version

Nightly (Please give date/commit below)

### Transmitter

Other (Please specify below)

### Anything else?

I tested on a BetaFPV Literadio 3 Pro

**Comment by gagarinlg** [comment]
@HThuren maybe you can check this?

**Comment by HThuren** [comment]
I can, but have only a Taranis 9 plus. Have just checked and changed some to have blanks after the word, but maybe you can provide a picture with the issues.
I have changed some words and uploaded to #2271

**Comment by gagarinlg** [comment]
You can use the simulator for this, no need to test on a real radio.
Run cmake for one of the radios with a smaller display and build companion and libsimulator. Then you can test on your PC.

**Comment by HThuren** [comment]
Of course, I'll do, Thx

**Comment by HThuren** [comment]
Are the right defines -DPCB=X7 -DPCBREV=LR3PRO, I got error from 128x64/model_setup.cpp at struct afhds3, no member runPower and rxFreq
Help !

**Comment by pfeerick** [comment]
Yes, 
https://github.com/EdgeTX/edgetx/blob/4e49ac68bed0b19b5fbd063c6d13ee2018627b9f/tools/build-gh.sh#L129

Make sure you delete the `CMakeCache.txt` in your build directory before trying to build for a different radio. Although preferably, just either delete everything in it, or delete the entire folder and re-create it. You end up with left-over files and configuration settings for another transmitter family otherwise, and things go horribly wrong ;) I have a build folder for each different radio type that I build for, so don't have to do that quite as much.

**Comment by HThuren** [comment]
Thank you, i try 🙂

**Comment by HThuren** [comment]
Great advice, no compiler issues now :-) :-)

**Comment by gagarinlg** [comment]
I made me a shell script that runs cmake for a bunch of different radios to different build folders. That way I do not have that issue and can switch quickly between radios without a complete rebuild everytime.

**Comment by HThuren** [comment]
Yes, a good solution. I just also now have diffrent build folders, and itt seems to work.

**Comment by HThuren** [comment]
Hi @gagarinlg, now changed in  #2301, hope I got them all

**Comment by pfeerick** [comment]
Implemented in #2301
