### ISSUE TITLE
Upgrading: Widgets lost, Internal ISRM not displayed, no ACCESS, no Czech

### ISSUE THREAD

**Issue by mkdaw** [EdgeTX/edgetx#243]
The necessary lua probably work well for me. When upgrading to EDGE, it did not load the widget settings from OpenTX on the screen at startup. I need to set them again. The internal ISRM is not displayed. This does not work with the ACCESS protocol. It does not contain Czech, which does not matter. But I understand English ... User color themes on the display would also be good. Otherwise EDGE is very nicely processed and I like it. Good work. Good luck. 

Mod edit: Please put the message in the body of the issue, not the title!

**Comment by raphaelcoeffic** [comment]
@mkdaw we probably need to state it better: the lost widget settings / screen settings is intentional, as it is not compatible to 2.3. We are using typed options, whereby 2.3 uses an implicit semantic, assuming the code for these widgets does not change…. So we had to wipe it so that it does not cause trouble.

**Comment by pfeerick** [comment]
So another known limitation for the notes? i.e.
* Panel / widget settings cannot be preserved in the conversion from OTX 2.3.x => ETX 2.4.0 due to incompatibility in how the settings sere stored. 

Is there a better way to say in plain language how converting the OTX 2.3.x => implicit semantic to ETX => typed options isn't possible? (as well as me better understanding... are we talking about something like settings stored in a set order and assuming that order won't change, vs say in a json list?

**Comment by raphaelcoeffic** [comment]
> So another known limitation for the notes? i.e.
> 
> * Panel / widget settings cannot be preserved in the conversion from OTX 2.3.x => ETX 2.4.0 due to incompatibility in how the settings sere stored.
> 
> Is there a better way to say in plain language how converting the OTX 2.3.x => implicit semantic to ETX => typed options isn't possible? (as well as me better understanding... are we talking about something like settings stored in a set order and assuming that order won't change, vs say in a json list?

2.3 does not include the type of the options in the binary file.

**Comment by pfeerick** [comment]
This should be resolved between access builds being made available and https://github.com/EdgeTX/edgetx/pull/991 adding ACCESS menus for 2.6.
