### ISSUE TITLE
Internal rf “off” setting not save

### ISSUE THREAD

**Issue by marinehm** [EdgeTX/edgetx#2563]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have turned the internal rf setting to off several times.  Turn off the radio and turn it back on.  Go into radio settings and the internal rf is back on. My quad flys fine.  Internal rf in the quad settings stays off.  Where I’m having issues and trying to pinpoint the origin of the error.  I have a RM TX16S with EdgeTX black pearl version.  Updated ELRS to 3.0  When trying to use EdgeTX companion and connect to the radio wifi.  Wi-Fi’s enabled for a short period then get disconnected and error code: ?:0:attempt to index field’?’(a nil value)

### Expected Behavior

Radio settings (internal rf “off”) to remain off when set to off.  Even after turning the radio off and back on again.

### Steps To Reproduce

Enable wifi using the ELRS LUA.  Connect to HappyModel ES24TX pro micro to pc via ELRS configurator.

### Version

2.7.1

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![0D95C9B4-2C3D-4BBA-84F5-7E0D4F4B9E91](https://user-images.githubusercontent.com/27977155/196002565-dfb2b0ad-5349-400c-a608-acf395800c71.jpeg)
![5B23E2D4-2C46-4CA1-B835-27DCF87E32B3](https://user-images.githubusercontent.com/27977155/196002569-5bcc78ee-33b1-42d5-b346-bcdfecf98323.jpeg)
![DDA25357-30BF-4A79-B488-96FCEA160C1E](https://user-images.githubusercontent.com/27977155/196002573-c0d36123-939d-465f-ab15-f899d93c826d.jpeg)
![7A4277D0-7550-4054-AC8A-9CE8EAEC3E7E](https://user-images.githubusercontent.com/27977155/196002574-1e08c83d-faa0-4bb1-adb1-490616e164ca.jpeg)

**Comment by pfeerick** [comment]
That is normal, and expected behaviour. If you want the internal RF to be off, you should be turning it off in the model settings. The 'HARDWARE' page setting is for changing what the default internal RF is, not for turning it off. We should probably remove the 'OFF' option there to stop people thinking they can turn it off there. 

Also, please try to stick to one issue per, well, issue... otherwise multi-issue uses may not get everything resolved when a fix for one part of it closes the issue.

**Comment by raphaelcoeffic** [comment]
The other issue is already documented in #2436
