### ISSUE TITLE
Mixer monitor displays blank string instead of '0%'

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#2575]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If the mixer value is zero, the mixer monitor displays a blank string.

### Expected Behavior

The monitor should display '0%' 

### Steps To Reproduce

1. Go to Mixers menu
2. Enable 'Show mixer monitors'
3. Observe monitor values as mixer source passes through centre

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

2.8.0 RC3

**Comment by raphaelcoeffic** [comment]
In fact, this is done on purpose, and works as designed. You will see the same behaviour for all mixer monitor bars across the color UI.

**Comment by pfeerick** [comment]
It's also not a bug so much, as one just has to look at how the bars function... the numbers are shown in the un-used portion of the bar - which is all of it in the case of 0% ... so where dos it get displayed? It has been this way since ETX 2.4. I can see how you might think of it as a bug having come from OTX which does show it. 

The question really is whether is it necessary to show 0% - as if there is no value, shown, it will be 0%. And the absolute us value which is always shown also tells you it's at 0%/1500/channel centre. With normal ... symmetrical? ... mixes and such, I would think not, but as soon as there is an offset between input and output, I can see how it would look odd... as one bar would show % and the other nothing. So I think I'll make the tweak necessary to make that shown. Plus it does just reassure that it is at 0%.
