### ISSUE TITLE
Key bindings in text editing state

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#265]
They are somehow un-intuitive so proposal is:
- ENTER - confirms & advances to the next character (as now)
- ENTER long - opens pop up to clear (as now)
- MDL - changes character case
- PAGE NEXT - moves forward to the next character
- PAGE PREV - moves backward to the previous character
- TELE - deletes focused character
- SYS - no binding (free for future use)

**Comment by lshems** [comment]
May I make a counter proposal:

Preferably, all text editing is done with just the enter and the plus/minus keys for basic editing. This would allow to do all with the scroll wheel (and its enter key function), or plus/minus/enter keys that are all located together in the physical layouts of the different radios. This for ergonomic reasons which would allow editing with one finger, which is always quickest and most intuitive.

Then, you should consider a string or text is an navigable object in itself!! That means that when you click on a string object in a menu, you should still be able to navigate through it like through lists of navigable objects with the plus and minus keys. Once you navigated to the character you want to edit, you click enter to activate the OVERWRITE mode for the editable (non-navigable) item. Plus/minus will allow you to edit, exit to get out of OVERWRITE mode, but also enter will take you out of OVERWRITE mode!!
This allows to do all OVERWRITE edit actions with three keys only.

There are some specific things with strings, compared to the main navigation and edit structures, and that is where shortcuts com in handy. 

Multiple edits on subsequent characters:
It is logical that when you edited a character, you want to edit the next. So on exit, you would want to shift automatically to the next editable object. (this could be adapted as a general rule by the way. Should be considered).
It is also logical that when you are in OVERWRITE edit mode, click enter, and you shifted to the next character, it also opens automatically in OVERWRITE edit mode again. Just one extra click on enter would get you out of edit-mode back into navigation mode.  

Inserts and deletes:
a special use-case for strings is that you want to be able to ADD or DELETE a character (on any position in the string), not only edit in OVERWRITE mode. 
Adding characters: This can be done by going to the character and change from the NAVIGATION mode to the INSERT mode (instead of the OVERWRITE mode). You could assign that function to the long enter and a new character will be added before the current one. The plus and minus allow you to edit the character. pressing enter again, and you go out of edit mode. Same concept as above: it is logical that you want to add multiple characters sequentially, so after hitting enter, you get a new space character on the next position and remain in edit mode. plus minus will change the character. To exit the INSERT mode, just click long enter. The last added character will be emptied, so you wont get stuck with the blank space. So to add one character: long press enter, select the character with plus/minus, enter to add the next, end long enter to get out of INSERT mode and delete the added blank.
Deleting characters: deleting a character can be done by navigating to it, activate the INSERT mode with long enter, and press long enter or long exit again. It will act as a delete, deleting the next character.

Special case: adding a character at the end of a line.
The cursor "|" in edit mode is always in front of the character where you are going to insert. This means that you cant add a character at the end of a line. To work around that, you need to allow the cursor to go one step after the last character, before the 'virtual" next character, in INSERT mode. the user can simply edit it with plus and minus. One click on enter again, and the character is added. In this case, directly a new character would be added on the 'new' last spot, and plus and minus will edit it again.

Special case: adding a line when editing a text (notes text, for instance :);))
when at the last position of a line in OVERWRITE mode when doing a TEXT edit
