### ISSUE TITLE
2.8 Companion simulation 6POS TX16S 

### ISSUE THREAD

**Issue by adalta87** [EdgeTX/edgetx#2827]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

I am trying to standardize all my builds models and make them compatible with other PWM values on the TX16S. On the TX16S there is the 6POS buttons. While trying to make sure these match other values in the sim it seems there is not always a consistent value for each position. EX: POS1 =988 but on the next selection in sim for POS1 it may be 1015. It seems as though on TX16S the 6POS is acting as a slider and not simulating valid values. I do have a custom curve set not sure if that makes a difference on the sim.

### Expected Behavior

Consistent values on each position click and not acting like a slider. POS1 will always be the correct simulated value

### Steps To Reproduce

Open companion 2.8. TX16S radio profile and look at the 6POS values they are never consistent on each click for each  position.  In sim it almost acts like a slider as you can vary the values with slight mouse movements. I would imagine this persist across all companions regardless of version. I for some odd reason cannot get this to record on a screen recorder as it always will record the models screen no matter the way I try and sim and record.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by elecpower** [comment]
The knob object inherits the properties of a slider and there is a 'disconnect' between the displayed notch position and the mouse release value. Will need to investigate if possible/practical to override release position with closest notch value before sent to radio.
As @pfeerick states it does work better if wheel is used however I did find a glitch due to rounding such that you can get 7 positions (99 & 100).
