### ISSUE TITLE
Build Instructions under Ubuntu 22.04

### ISSUE THREAD

**Issue by simos** [EdgeTX/edgetx#3154]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Wiki page with [Build Instructions under Ubuntu 20.04](https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Ubuntu-20.04) covers Ubuntu 20.04. It does so, using [this shell script for Ubuntu 20.04](https://raw.githubusercontent.com/EdgeTX/edgetx/main/tools/setup_buildenv_ubuntu20.04.sh).

I updated the script to work with Ubuntu 22.04. I have switched clang to version 14 (from version 7) because Ubuntu 22.04 does not have a version 7 clang package. 

However, the EdgeTX source code mentions specifically clang 7. Is it required to use clang 7?

[The updated script for Ubuntu 22.04](https://gist.githubusercontent.com/simos/8de45464687d87407041e4c2d2f69500/raw/4530829479584f290a91020a75c4f6e360492704/setup_buildenv_ubuntu22.04.sh).

### Describe the solution you'd like

I would like to update the Wiki to include build instructions for Ubuntu 22.04.

### Additional context

1. Ubuntu 22.04 does not have the `qt5-default` package. [It is replaced with the following set of packages](https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04): `qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`.
2. Instead of creating a symbolic link `python` -> `python3`, you can [install the package `python-is-python3`](https://askubuntu.com/questions/1296790/python-is-python3-package-in-ubuntu-20-04-what-is-it-and-what-does-it-actually) which does exactly that.

**Comment by pfeerick** [comment]
The build system is only officially supported under 20.04 (i.e. per the docker build environment), so this will be good to have when we do finally move up to 22.04. This will take a while though as it will need extensive testing to ensure that it does not introduce any new issues of its own across the codebase. It's too late in the 2.9 cycle, so I will tag it for consideration as part of 2.10.

**Comment by elecpower** [comment]
Qt 6.4 is currently only supported on Ubuntu 20.04 refer https://doc.qt.io/qt-6/supported-platforms.html

**Comment by lvanasse** [comment]
I just tried it on my machine and I got those errors message:

![image](https://github.com/EdgeTX/edgetx/assets/12837376/9ca26100-f599-46d5-b8ca-70be8bb3611e)


![image](https://github.com/EdgeTX/edgetx/assets/12837376/a9374f64-77a2-4b92-afd4-ead34d58f816)

The two errors above were solved with a simple installation:
`pip install lz4` and `pip install clang`. 

But now I'm stuck at: 
![image](https://github.com/EdgeTX/edgetx/assets/12837376/4ad5a973-a24b-4f46-95c0-2bac127369c1)
Although, I do have `libclang1` install on my machine:
![image](https://github.com/EdgeTX/edgetx/assets/12837376/c0affe52-a282-474d-8821-c4ff8c73debc)

And I've also close and reopen the terminal so that configuration are there. Maybe it's missing a path?

**Comment by firstqyz8408** [comment]
> 构建系统仅在 20.04 下正式支持（即每个 docker 构建环境），因此当我们最终升级到 22.04 时，这将很好。这将需要一段时间，因为它需要广泛的测试，以确保它不会在整个代码库中引入任何自己的新问题。在 2.9 周期中为时已晚，所以我会将其标记为 2.10 的一部分以供考虑。

Hi, I built EDGETX in UBUNTU20.4 according to several articles in the WIKI, but I opened the project from QT, it seems that only header files can be loaded, not all files, but there are no errors in the compilation, can you help me?

**Comment by rotorman** [comment]
@firstqyz8408 This issue here is for Ubuntu 22.04, not 20.04.
Best, you join EdgeTX Discord and present there some screenshots showing the problems in more detail that you are having.
