### ISSUE TITLE
Misleading "RX channel order" on BW radio

### ISSUE THREAD

**Issue by 3djc** [EdgeTX/edgetx#3348]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The working used is misleading and technicaly not accurate imho. All this field does is define a default RADIO channel order, but actual RX channel order might be affected by things like multimodule channel reordering, or receiver side pin mapping on ELRS and others. In no way can it be guarented that RX will actually use the order shown here.

![image](https://user-images.githubusercontent.com/5167938/224729495-93797bae-2d7c-4d09-a959-b2812c126bfa.png)

(Don't look at the RETT value, this is a WIP branch ;))

### Describe the solution you'd like

Remove RX from the wording

**Comment by pfeerick** [comment]
Color has the proper wording "Default channel order" .... has never been changed from the OTX wording, which I guess was done that way to struggle to condense "Default channel order" for 128x64?? 

Anyway, since 15 chars seems to to be the visual limit I'm tempted to change it "Def chnl order"

https://github.com/EdgeTX/edgetx/blob/b258c3b92c6b4bf0e6fb0d5801d6117fcdfa8519/radio/src/translations/en.h#L457

**Comment by 3djc** [comment]
Maybe 'Def chan order' ?

**Comment by pfeerick** [comment]
Sounds good to me. I'll include that in #3326 as it will need some translations done anyway.
