### ISSUE TITLE
Regression? New mixes being forgotten.

### ISSUE THREAD

**Issue by sixtyfive** [EdgeTX/edgetx#3367]
The below issue occurs only with 2.8.1, not 2.8.0.

### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When setting up a mix other than the 5 defaults (them being the 4 stick movements as well as Arm/Disarm on switch SC), and then rebooting the transmitter, any additions made to the Mixes tab are then gone again.

_Changes_ to one of the 5 defaults are retained, only _additions_ are forgotten.

### Expected Behavior

Adding a mix and rebooting retains that mix throughout reboots.

### Steps To Reproduce

1. Turn transmitter on
2. Long-press "Enter" button
3. Right-press right thumbstick to page 5/11 ("Mixes")
4. Down-press right thumbstick to CH6
5. Press "Enter" button
6. Down-press right thumbstick once
7. Press "Enter" button (selection blinks)
8. Operate SD button
9. Press "Enter" button (selection stops blinking)
10. Press "Exit" button, observe new mix is now set up
11. Press "Exit" button again
12. Turn transmitter off
13. Turn transmitter on again,
14. Navigate to "Mixes" again, observe new mix is missing

### Transmitter

BetaFPV LiteRadio3 Pro

**Comment by VitalyKondratiev** [comment]
I didnt catch this bug on 2.8.1, but yesterday I upgrade EdgeTX to 2.8.2, and get this problem.
Downgrade to 2.8.1 saves the bug, but downgraded to 2.8.0 removes the bug
I have BetaFPV LiteRadio 3 Pro too.

**Comment by oloendithas** [comment]
Experiencing the same issue on 2.8.2.

**Comment by oloendithas** [comment]
Issue persists on 2.8.4

**Comment by oloendithas** [comment]
2.10-nightly still not fixed

**Comment by pfeerick** [comment]
I saw recent reference to this suggesting it only happens on the existing models, not new models... can you try creating a new model and seeing if this still happens. 

BTW, main / nighties are in no way safe to fly atm. Stick with 2.8.x or the 2.9 branch for now, other than for testing.

**Comment by oloendithas** [comment]
Oh, indeed. Newly created model does not suffer from this issue (on 2.8.4).
Thanks for the clue!

**Comment by paulo-serrao** [comment]
I am encountering the same issue, my radio is the RadioMaster Pocket.

Here is an example of a model with this issue, if I set mixer CH7, I loose it after a reboot (or simply switching to a different model). 

[model02.zip](https://github.com/EdgeTX/edgetx/files/12506937/model02.zip)

**Comment by raphaelcoeffic** [comment]
@paulo-serrao thx for the file!

What happens here is the following:
- the file has been copied from another radio,
- which had *some* source that the destination radio does not have.

When such file is loaded in the destination radio, the following happens:
- the source is not found by the parser and set to `NONE` (`= 0`)
- when displaying the mixer lines, the first line with `Source = NONE` stops the display

If I make a quick & dirty patch to take the `Weight` into account as well, you can see your missing mixers:

<img width="259" alt="Screenshot 2023-09-03 at 23 11 54" src="https://github.com/EdgeTX/edgetx/assets/1050031/a1161c71-cfe6-4661-ad5d-e08beaceecf8">

Now the issue is that due to the how we store mixer lines in memory, it gets quite hard to patch so that it always works.
Historically, such mixer lines with `Source = 0` never happened, as you cannot choose it on the UI, and OpenTx would not let you load a file from another radio, as the sources were all just numbers and have a specific meaning only in the context of a specific radio.

**Comment by raphaelcoeffic** [comment]
Oh, and btw: I believe this bug is present for quite some time now (probably as old as the YAML parser).

**Comment by paulo-serrao** [comment]
@raphaelcoeffic, this is the original model file from X9D before I started making changes in the new radio to adjust to new button layout: [model02_x9d.zip](https://github.com/EdgeTX/edgetx/files/12508087/model02_x9d.zip)

The previous file I uploaded was after many changes on other menus/settings and also trying multiples times to set a mix on CH7 to Switch D.

PS: On X9D I had CH6 set to Switch G, that switch does not exist on RadioMaster Pocket, maybe that's the root cause? This is how it looks like on my Taranis

![Screenshot_2](https://github.com/EdgeTX/edgetx/assets/35876077/42188a35-ec57-4437-9e60-a6d2b43a6ce5)
![Screenshot_4](https://github.com/EdgeTX/edgetx/assets/35876077/c51c3b78-e201-4f42-bbd3-35b039e871d6)

**Comment by raphaelcoeffic** [comment]
> On X9D I had CH6 set to Switch G, that switch does not exist on RadioMaster Pocket, maybe that's the root cause?

This is it, yes. That transforms it into `NONE` (`---` on screen), which makes the UI think the mixer does not exist, and stops displaying any line after that.

**Comment by oloendithas** [comment]
As was mentioned before, the workaround it to create a new model. The issue persists only in models created on pre-2.8 versions.

**Comment by raphaelcoeffic** [comment]
@ValorLin @oloendithas as you can see, there is a code change proposed in #4008 which you can try (backup your SD card before, you will need it to go back to 2.9). We need feedback from you guys on that.

**Comment by oloendithas** [comment]
> We need feedback from you guys on that.

I've recreated my model and can't reproduce the issue any more 🤷🏻‍♂️

**Comment by paulo-serrao** [comment]
> I am using the BetaFPV LiteRadio3 Pro, After I upgraded to 2.9 yesterday, the issue occurs. Is there a workaround?

You can edit the yaml, clear out the section for the mixer and then recreate it on the radio. (this will avoid having to recreate the whole model and all settings)

**Comment by raphaelcoeffic** [comment]
Exactly, the issue is the mixer source `NONE`. If clear that line, or set it to something meaningful, it works.

**Comment by ValorLin** [comment]
> > I am using the BetaFPV LiteRadio3 Pro, After I upgraded to 2.9 yesterday, the issue occurs. Is there a workaround?
> 
> You can edit the yaml, clear out the section for the mixer and then recreate it on the radio. (this will avoid having to recreate the whole model and all settings)

Thanks! It works!. 
I believe that you guys have caught the problem.  @raphaelcoeffic 

Here is the original yml that caused this issue.
[model03.yml.txt](https://github.com/EdgeTX/edgetx/files/12664078/model03.yml.txt)
