### ISSUE TITLE
Timer 1 and 2 activate with  Thrtl channel override active.

### ISSUE THREAD

**Issue by MervDale** [EdgeTX/edgetx#338]
I use Timer 1 as a total flight log ( no reset)
I use Timer 2 as current flight time (battery time, approx )  with reset

Both timers still acivate with throtle movement with channel override switch active
Start mode set to Throttle  switch SC UP  set to overide Channel 2    -100  Motor OFF
SC MID  SC DOWN = Motor ON 

I have checked this with OpenTx 2.3.12 and 2.3.13 and they have the same issue with the timer activated with the THs  option, Not sure  if this occured on earlier version of OpenTx 

I would have thought that the option of starting a timer with the Throttle activation, 0 upwards should be deactivated if the throttle channel is over ridden ?

![timers start](https://user-images.githubusercontent.com/30642754/123508422-b7235180-d6b2-11eb-88fd-ca4bc7ff4f79.jpg)

edit: removed template text

**Comment by pfeerick** [comment]
I'm wondering if this a logic problem more than a bug... 

If I understand this right, you have SC it so that in the up position is overriding the throttle channel to -100 (i.e. throttle stick down). The simplest way to do this would be to have the !SCup (_not_ SC up) position trigger the throttle override. 

It would then make sense that if you want the timers to trigger on throttle start, that they want to be set to the !SCup switch state, so that they are also can only start counting when SC is _not_ in the up position. 

Throttle start will start counting, until you reset it, so when you arm, and move the throttle, the timer will start and stop when arm/disarm via SC. If you use Throttle as the mode, the counter will only run when armed, and the throttle stick is moved above -100.

Please don't hesitate to correct me if I've wrongly assumed something here... But for me, this starts the timers if the throttle stick is moved AND SC is in the mid or down position, stops them when the switch is in the up position, but they start again on their own if the switch is then moved back into the middle or down position. That last part could be prevented by using Throttle instead of Throttle Start. 

![image](https://user-images.githubusercontent.com/5500713/123511543-2d30b400-d6c5-11eb-8b84-27c5fba841bd.png)
![image](https://user-images.githubusercontent.com/5500713/123511548-3752b280-d6c5-11eb-9c4a-cb1094dbbd82.png)

![image](https://user-images.githubusercontent.com/5500713/123511534-21dd8880-d6c5-11eb-8213-df276d4c86e9.png)

**Comment by MervDale** [comment]
Ok, this works but the Throttle switch need to be set to "Throttle"  not "Throttle Start".

**Comment by pfeerick** [comment]
Excellent. Yes, with timer mode set to Throttle Start the timer will start the first time the throttle moves (and the switch condition is true), so if you disarm/re-arm by moving SC up and then down again, the timer would resuming counting regardless of the throttle position. This is exactly how THs behaves on OTX... so is not a new or different behaviour.
