### ISSUE TITLE
range mode RSSI

### ISSUE THREAD

**Issue by weixelgeist** [EdgeTX/edgetx#356]
EdgeTX 2.4.0 RC3
Jumper T18

in range mode the RSSI is not shown

**Comment by raphaelcoeffic** [comment]
> EdgeTX 2.4.0 RC3
> Jumper T18
> 
> in range mode the RSSI is not shown

I guess this is with the internal Multi module, right?

**Comment by weixelgeist** [comment]
> > EdgeTX 2.4.0 RC3
> > Jumper T18
> > in range mode the RSSI is not shown
> 
> I guess this is with the internal Multi module, right?

Yes

**Comment by pfeerick** [comment]
As in, the RSSI screen is not shown? As OTX used to bring up a screen that just had RSSI on it... ETX seems to trigger the range mode, but doesn't bring that screen up. 

![image](https://user-images.githubusercontent.com/5500713/123539323-84459000-d77c-11eb-8da0-3dd5867f7764.png)

**Comment by eshifri** [comment]
What if we just output RSSI on the Range button (instead of the word "Range"), while it is yellow and blinking?
Or is it too small and you prefer the whole Page?

**Comment by pfeerick** [comment]
I think if you were outside in the sunlight it would be too small, as it's a pretty small button. I don't *mind* the whole page, but also feel it's too big. However, I think part of the purpose is so that you have to use the RTN button to exit it, thus in doing so stopping the range check. Otherwise, at the moment, you could leave the screen, return to it, and while the UI doesn't indicate the range check is still active, pressing the button again stops the range check.

**Comment by pfeerick** [comment]
What 'could' be done is show it all the time, which actually brings up another bug - when doing frequency tuning for certain protocols (i.e. Frsky), the RSSI is supposed to be shown, but it isn't. 

![image](https://user-images.githubusercontent.com/5500713/123623943-59793b80-d851-11eb-86e2-40ba8f85c889.png)

**Comment by eshifri** [comment]
But it is still the same small size, isn't it?

**Comment by pfeerick** [comment]
Yeah, that's why it's not ideal if it was the only way to see RSSI whilst in range test mode. That RSSI display is for a different reason - calibration of the internal multiprotocol module - and you generally don't touch it again after doing the initial calibration (which will probably be indoors) so isn't such a problem. The range test is likely to be outdoors if you're following procedure and range-checking before flight (which we all do, right? 😁) ... so it would be better to not make it hard to see ;)
