### ISSUE TITLE
2.9 Themes

### ISSUE THREAD

**Issue by tourerjim** [EdgeTX/edgetx#3760]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

TX16s MKII updated to 2.9 but my own Themes screen goes black and not able to read anything from the screen, went back to 2.8.4 and my Themes screens fine and with 2.8.3

Cant edit my Themes on 2.9, cant see 'Edit' or the drop down to edit.

### Expected Behavior

I assume I just  copy over my sc card content and my theme.yml works

### Steps To Reproduce

If I change from EdgeTX theme to my theme screen goes black 

### Version

2.8.4

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

none

**Comment by philmoz** [comment]
Please post your theme.yml file here so we can see what is wrong. You will need to rename it to theme.yml.txt.

**Comment by tourerjim** [comment]
________________________________

**Comment by pfeerick** [comment]
You'll need to upload this on Github - email attachments are ignored.

**Comment by tourerjim** [comment]
[theme.yml.txt..txt](https://github.com/EdgeTX/edgetx/files/11954226/theme.yml.txt.txt)

**Comment by philmoz** [comment]
Open the file in a text editor and remove the blank like before the 'colors:' section.

**Comment by tourerjim** [comment]
Thank you,  removing blank lines my themes are now working with 2.9

**Comment by tourerjim** [comment]
Unfortunately there is still bit of an issue, to get my theme working I need to edit within your theme, correcting the spacing only worked when I edited within your theme ie FM2M_Concrete, if I transfer my theme from 2.8.4 or write my own it will not work and looking at the two pictures may help.
picture 1 is your .yml file (FM2M_Concrete) and file shows thunbnail blank, my edit picture 2 saved as .yml shows text lines on thumbnail.
![Untitled1](https://github.com/EdgeTX/edgetx/assets/65942690/10272bfe-67df-4502-b9f5-806e09b80fbf)
![Untitled2](https://github.com/EdgeTX/edgetx/assets/65942690/abecab46-c67b-45b6-ad4f-db898ed28054)

**Comment by philmoz** [comment]
Check that Windows is not hiding a .txt extension on the edited file.

**Comment by tourerjim** [comment]
Could you show example, I save in Notepad as theme.yml

**Comment by pfeerick** [comment]
In your own screenshot, you can't see an extension for the logo file, so the extension for your theme file may or may not be `.yml`. You need to go into the file explorer options, and untick the "hide extensions for known file types" option.
![explorer_vJcHLYOtKM](https://github.com/EdgeTX/edgetx/assets/5500713/9017bd16-b556-412d-95b5-031d7e5d0115)

Alternately, when you save it in notepad, make sure you change the save as type from "text document (*.txt) to "All files (*.*)", otherwise notepad will always append .txt to the filename whatever you give it ;)
![Notepad_WwifltDZWA](https://github.com/EdgeTX/edgetx/assets/5500713/79911b66-2e44-4ef7-87d8-a475d3348af8)

**Comment by philmoz** [comment]
Select the 'Options' dialog under the View menu in Windows Explorer.
Uncheck the 'Hide extensions for known file types' option in the View tab.

![Screenshot 2023-07-05 at 7 41 34 pm](https://github.com/EdgeTX/edgetx/assets/9474356/f16b6a08-47a4-4989-abb2-21b367341222)

**Comment by tourerjim** [comment]
Thank you, I'll try that.

**Comment by tourerjim** [comment]
Alls good now, on 2.8.4 or lower I didn't have issues with image naming 'logo' and saving or .yml files in Notepad, but something has changed in 2.9 saving logo is now saved as logo.png & theme.yml as your 'image file options' theme.yml is now saved as 'all file types.

**Comment by pfeerick** [comment]
Neither the extension for the logo file (`.png) or the theme file (`.yml`) have changed in 2.9. 

Have a look at the name of the option in your file browser we directed you to, it isn't just "hide file extensions", it's "hide **known** file extensions". In the first screenshot you showed in https://github.com/EdgeTX/edgetx/issues/3760#issuecomment-1621361234, your windows install doesn't recognise the file type, so shows a generic icon. In the second screenshot, it shows a different icon, hence the file extension (which you can't see, otherwise you'd also be able to see the extension for the logo file next to it was .png), so really that file was called `theme.yml.txt`, which is invalid. If you check on the radio using the SD browser, you'll see this also. You really need to turn that option off so that it isn't misleading you.

**Comment by tourerjim** [comment]
Not sure if it's to do with Windows which done update on my laptop couple days prior to me updating to 2.9.
For me to edit theme.yml to work with 2.9 this is the file thumbnail that shows in Themes.

![Untitled3](https://github.com/EdgeTX/edgetx/assets/65942690/cc0f6dcb-5777-4127-a3f6-9710c9431044)
If I drop this file to here I get message (we don't support that file) but and strange thing is that same file works with 2.9 Themes.

**Comment by pfeerick** [comment]
More importantly, you can now see the file extensions for both, so know they are both correct. If you wanted to upload it to github, you would have to do what philmoz said back at https://github.com/EdgeTX/edgetx/issues/3760#issuecomment-1620790138, which was 

> You will need to rename it to theme.yml.txt.

in other words, change the file extension so it ends with `.txt`, which is what GitHub said was one of the supported file extensions when you tried to upload the file. I think this is how you got yourself confused before, as when you changed the filename from `theme.yml` to `theme.yml.txt`, it became a "recognised file type", and thus the extension was hidden, meaning you could only see `theme.yml`. It's only when you turned that extension hiding nonsense off that you can see what the true file extension was. 

Anyway, the important thing here is there was a change in how EdgeTX 2.9 reads/writes `theme.yml` files which you've helped us identify, and it's just a matter of ensuring there are no blank lines in the file to confuse the firmware.

**Comment by tourerjim** [comment]
Your helps are well appreciated, an old boy trying to keep up with all this tech and am really pleased I've got all my own themes back now working.
Thank you.
