### ISSUE TITLE
X9d 2019 internal RF

### ISSUE THREAD

**Issue by lhh6688** [EdgeTX/edgetx#3806]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

EdgeTX X9d 2019 internal RF fail that should be ACCeSS not XJT

OpenTX is fine

![A82870A7-4820-4477-AF6A-91E52E07006B](https://github.com/EdgeTX/edgetx/assets/76086266/6b646cf4-4d56-4dac-9c46-6644ea6ccdfa)

EdgeTX is fail
![48F18932-137F-43D4-8C7C-18AD05C43B9D](https://github.com/EdgeTX/edgetx/assets/76086266/5f1c51db-ee8e-4d5b-9c65-8df7a163e278)

### Expected Behavior

X9d 2019 internal RF

### Steps To Reproduce

X9d 2019 internal RF

### Version

2.9.0

### Transmitter

FrSky X9D+2019

### Operating System (OS)

Windows

**Comment by pfeerick** [comment]
Can you show the SYS -> VERSION page please... for the X9D+2019, you can't change the internal RF type setting (which could have explained why it said XJT instead of ISRM), so it is almost like you have loaded the X9D+ firmware, instead of the X9D+2019 firmware. 

![20230716_112821](https://github.com/EdgeTX/edgetx/assets/5500713/76185332-3941-497c-9d28-d4f73ea0f697)
![20230716_112836](https://github.com/EdgeTX/edgetx/assets/5500713/21364329-f30e-404f-a20b-33c2bdb8d8b9)

**Comment by lhh6688** [comment]
Firmware is fine
![D5760FB5-7F82-434A-8FF4-951FFEDE7F35](https://github.com/EdgeTX/edgetx/assets/76086266/3ae20344-c998-4ee3-a73c-02355898c2e5)

**Comment by 3djc** [comment]
Could you show this screen

![image](https://github.com/EdgeTX/edgetx/assets/5167938/c216b6d3-f053-424f-9af4-041767108175)

If you had loaded a wrong one and set XJT, it could still be there

**Comment by lhh6688** [comment]
> Could you show this screen
> 
> ![image](https://user-images.githubusercontent.com/5167938/253971853-c216b6d3-f053-424f-9af4-041767108175.png)
> 
> If you had loaded a wrong one and set XJT, it could still be there

![6C7CC2AD-245E-4A1D-88EC-5445033B4DF9](https://github.com/EdgeTX/edgetx/assets/76086266/15b019ee-c3d3-4bf0-a9bf-15d12e9c30b3)
No XJT

**Comment by pfeerick** [comment]
Given that the option to change the internal RF is not present on the
X9D+2019, all I can think off is perhaps that option was set by an
incorrect firmware flash, and now you'll need to change it manually.

Open up the RADIO/radio.yml file in a text editor (i.e. Notepad), and make
sure internalModule is as follows

internalModule: TYPE_ISRM_PXX2

You'll also need to change the parameter on the second line, manuallyEdited
from 0 to 1, so that the change to the file is accepted. You should be
right from then onwards. You 'may' find you need to turn the internal RF
setting off and on again in the model settings if it's still saying XJT
there.

**Comment by lhh6688** [comment]
> Given that the option to change the internal RF is not present on the X9D+2019, all I can think off is perhaps that option was set by an incorrect firmware flash, and now you'll need to change it manually. Open up the RADIO/radio.yml file in a text editor (i.e. Notepad), and make sure internalModule is as follows internalModule: TYPE_ISRM_PXX2 You'll also need to change the parameter on the second line, manuallyEdited from 0 to 1, so that the change to the file is accepted. You should be right from then onwards. You 'may' find you need to turn the internal RF setting off and on again in the model settings if it's still saying XJT there.
> […](#)
you are right !
I change it that make X9d 2019 fine
Thank you ,

**Comment by pfeerick** [comment]
Glad that fixed it for you :)
