### ISSUE TITLE
Jeti protocol

### ISSUE THREAD

**Issue by robb1364** [EdgeTX/edgetx#3820]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Hello, I would like to ask if the Jeti protocol can be implemented. I know that in the past it was possible to use Jeti receivers because the protocol was based on FRSKY protocol but maybe I am mistaken.
Anyway many thanks for great job you have dobne so far!!!
Kind regards

Robert

### Describe the solution you'd like

I am sorry but I don't have any solution as I am not the expert by any means on programing.

**Comment by pfeerick** [comment]
If by "can it be implemented" you mean "for transmitters with a 4IN1 MPM,
can support for Jeti" - this is a question for
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module , not EdgeTX.

**Comment by mha1** [comment]
This question was asked many times (e.g. https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/388). Pascal's answer: "Hi, sorry it's not doable. None of the current components can emulate it.".  The reason is Jeti is using a transceiver the MPM is not supporting. You should be able to DIY connect a JETI TU2 module using the JR module bay connectors. Connect the TU2 to GND, VCC (make sure voltages are compatible!) and CPPM. Telemetry not available through EdgeTX, Jeti Box required.

**Comment by mha1** [comment]
Some time ago I was thinking to implement the Jeti telemetry protocol to accommodate modules like the TU2. But Jeti uses - probably to annoy all hobbyists - a 9E2 serial link. Why on earth would anyone choose 9bit serial? This is a serious turn off. Doable but not worth it.

**Comment by robb1364** [comment]
Hello Michael,

Thank you for your super fast response!

**Comment by robb1364** [comment]
Hello Peter,

Sorry for putting the question on the wrong place!

Robert

**Comment by pfeerick** [comment]
It's no problem... gotta start somewhere :)
