### ISSUE TITLE
Wrong colors in menue Logical Switches

### ISSUE THREAD

**Issue by Ralf-W** [EdgeTX/edgetx#3866]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Activating a Logical Switch does change the color of the line. But the new color is that of the background of the screen and not the color for "Active".

### Expected Behavior

Color changes should stay unchanged to V2.8.4: Activating a Logical Switch did change the color of the line to the "Active" color, giving a good contrast to the background of the screen.

### Steps To Reproduce

Define any logical condition being normally False/Inactive.
Make this condition become True/Active.
Watch the coor of the line change to the color of the background of that screen: No contrast. 

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2, Other (Please specify below)

**Comment by pfeerick** [comment]
@JimB40 What say you? Should the line be using ACTIVE instead of SECONDARY3, given there is an outline for the "ENABLED" square to separate it from the rest of the line? This may be relevant to the FM, INPUTS, MIXES, GV, LS and SF pages, as they all use SECONDARY3 to highlight the active/enabled line. 

Where does it fit in with the theme structure doc, and does this need any changes made to it, since it hasn't been updated since 2.6? ;) This is not taking into account UIv3 ... that is a totally different topic. 
https://github.com/EdgeTX/themes/blob/main/structure.md

![image](https://github.com/EdgeTX/edgetx/assets/5500713/d071527c-9a1c-4c9d-a650-aeabbbae8b92)

**Comment by philmoz** [comment]
This will be easy to change after the libopenui refactor.

Mu concern with the active color is it gets a bit overpowering when there is a lot of it. I also don't think it is as readable.
![Screenshot 2023-07-28 at 1 10 39 pm](https://github.com/EdgeTX/edgetx/assets/9474356/255ec4e8-231f-46b5-ad11-08a495cb8796)

Maybe reduced opacity would help?
![Screenshot 2023-07-28 at 1 10 17 pm](https://github.com/EdgeTX/edgetx/assets/9474356/d31f1068-2476-4526-8f56-0eaf41f8c005)

**Comment by pfeerick** [comment]
Yeah, I was thinking that also, but I do agree with the OP - we shouldn't be changing from the pre-established theme constants, as that effectively breaks *ALL* the themes. It is somewhat overpowering with the default theme, but at the same time, it is very clear what is active, and what isn't. That's why this may need to be tweaked for 2.9 to restore prior behaviour, and then done properly as part of the libopenui refactor.

**Comment by philmoz** [comment]
2.8.4 introduced this new style of active theming on the inputs and mixes pages.

2.9 extends this theming to GV, LS and SF pages.

**Comment by Ralf-W** [comment]
Sorry, I hit the wrong switch. :-(

**Comment by Ralf-W** [comment]
I think the Special Functions page looks clear and easy to read in 2.9.0. No color change necessary.
But it would be nice, if active Logical Switches would be highlighted using the Active color in the Logical Switches page - as it was done in 2.8.4.

**Comment by JimB40** [comment]
Yep now it drifted from initial idea
ACTIVE was intended to show that feature is activated (not enabled)

So right usage:
 External RF is active and Trainer is Active
![screenshot_tx16s_23-07-28_22-03-57](https://github.com/EdgeTX/edgetx/assets/46420768/5fabeaca-13ea-434e-9e3e-186e94e7289e)

FM0 is active
![screenshot_tx16s_23-07-28_22-04-05](https://github.com/EdgeTX/edgetx/assets/46420768/456383b7-6324-4e8d-bc00-5e9ee69ca9e4)

LS01 is active (ON)
![screenshot_tx16s_23-07-28_22-04-40](https://github.com/EdgeTX/edgetx/assets/46420768/84677dfa-ddda-4dce-805d-e25bf083d893)

Even better withe grid as you can clearly see which ones are ON
![screenshot_tx16s_23-07-28_22-05-17](https://github.com/EdgeTX/edgetx/assets/46420768/29037f38-0f8b-4f12-b904-0f8009eb4ac1)

CRSF Quad model is Active
![screenshot_tx16s_23-07-28_22-03-36](https://github.com/EdgeTX/edgetx/assets/46420768/dc0e9aef-cffb-432e-9ed0-1afca2c75777)

SF1 is not active
SF2 & SF3 are active
SF3 has this 'enable' option but this is indicated by checkin checkbox 
![screenshot_tx16s_23-07-28_22-11-46](https://github.com/EdgeTX/edgetx/assets/46420768/a2bd00ce-406c-4085-b809-de32372d340f)


Wrong usage:
Disarm line in Input is Active but it's not highlighted with ACTIVE
![screenshot_tx16s_23-07-28_22-04-20](https://github.com/EdgeTX/edgetx/assets/46420768/4bc171ba-8ce5-414d-bf91-c67605ba0b28)

If ACTIVE color is too strong (because there are themes that is not) we need to change this color (in this case yellow) to less vivid instead of applying transparency.

**Comment by pfeerick** [comment]
IMO, the best course of action atm is to correct it so that ACTIVE is used where SECONDARY3 is used in those places. If we want to at the same time, perhaps find a better color than that particular shade of yellow for the _default_ active color. Or not, and leave it up to themes to set that.

**Comment by MervDale** [comment]
Leave as it was as it makes it more visible in bright light as to what is active and what is not

**Comment by pfeerick** [comment]
@philmoz Is there any chance you could craft something to restore this specifically for 2.9? With equivalent for 2.10 in the libopenui refactor PR. 

In other words, active mixer lines, active SF, active LS should all be using the ACTIVE theme constant, not SECONDARY3. As the question of wheither it should be yellow or not is separate to whether it should be using the ACTIVE constant to highlight active elements. As per https://github.com/EdgeTX/edgetx/issues/3866#issuecomment-1656286506

**Comment by philmoz** [comment]
I was looking at this and I'm concerned with the way the active enable checkbox on an active SF would look.

I tried adding an additional border around the checkbox like this; but it's still clunky.
![Screenshot 2023-08-03 at 4 06 30 pm](https://github.com/EdgeTX/edgetx/assets/9474356/78f26d25-9249-4ab5-8454-a3ec51b67353)

I definitely think the yellow needs to be toned down.

**Comment by philmoz** [comment]
Also what about GVARS:
![Screenshot 2023-08-03 at 4 10 31 pm](https://github.com/EdgeTX/edgetx/assets/9474356/b27f61a3-ce8b-40a8-94e4-6848746e8fc1)

**Comment by pfeerick** [comment]
Sorry, yes, GVARS also please :) The checkbox is somewhat of a nuisance, but it's a much lesser issue and can be lived with for now. It has it's own defined outline, so you just look inside it to see if it's active or inactive color.

**Comment by philmoz** [comment]
I've added the equivalent changes to the libopenui refactor PR for 2.10.

**Comment by JimB40** [comment]
Guys let me draw those lists. We are drifting now from intial 2.8 design (color-wise) and we will land with diferent look & feel of same UI type on every screen.

Benchmark in 2.9 is MODEL>CURVES Screen. Although list items are vertical every other list should behave in the same manner. Design adn color-wise. 
List item is divided for "Label area" and "Data area". 
- When we select Label area is changing to show what is selected 
- When item is active "Data area" goes ACTIVE.

There will be variation for list wit items with sub-items (lines) like MODEL>INPUTS but it will go the same design path with exception that user has to see that item is seleceted, and which sub-item is selected.

I will draw it.
