### ISSUE TITLE
Set Trim to Sub trim issues when using scroll wheel.

### ISSUE THREAD

**Issue by TB2185** [EdgeTX/edgetx#3872]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm always hitting the scroll wheel getting into the outputs tab and then it moves all my trims into sub trims. i mainly fly fuel planes this makes me have to reset up my idle settings. 

### Describe the solution you'd like

Moving the Set Trims to Sub Trim Tab down to bottom of the outputs page. 

### Describe alternatives you've considered

1. Changing the location of the Set Trims to Sub Trim Tab. On the Bottom of the outputs page. or?

**Comment by pfeerick** [comment]
I mentioned this just now on discord, but will add it again here since it's relevant... (as well as expand on it a bit more)

On OpenTX, that button was originally at the bottom, and went missing for a while in UI transition from OTX to ETX. When it got re-added, it was then proposed that it be put at the top of the list, as most people didn't even realise the option was there. Plus it saved scrolling for it. So it's already been at the bottom, and deemed not suitable. 

So would instead a YES/NO confirmation of the change before it's made be better?

**Comment by TB2185** [comment]
Yes a confirmation would just be fine.  I will as told the Outputs tap has a option to be disabled in 2.9 so that alone will help but the configuration would be best case scenario.

**Comment by 3djc** [comment]
Otx had a long enter required to activate. I find the top position to be a very bad idea, as it is a very rarely used function

**Comment by TB2185** [comment]
> Otx had a long enter required to activate. I find the top position to be a very bad idea, as it is a very rarely used function



Even a Long press of the scroll wheel would be better. Like a few seconds press of the scroll wheel.
