### ISSUE TITLE
What is Reg.ID? The edgetx wiki does not explain it.

### ISSUE THREAD

**Issue by AExY1j1** [EdgeTX/edgetx#4680]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Some model files have this item, while others do not.
<img width="572" alt="image" src="https://github.com/EdgeTX/edgetx/assets/126180461/13ac59be-ac61-475b-b214-a3bedcde13a1">
<img width="1354" alt="image" src="https://github.com/EdgeTX/edgetx/assets/126180461/b32fabbc-947b-4654-8fa0-4c699b1fb2e3">

### Describe the solution you'd like

Explain what the project does.

**Comment by AExY1j1** [comment]
The version is v2.9.4

**Comment by pfeerick** [comment]
Reg(istration) ID is pretty much specific to Frsky, for their ACCESS RF system. It's used so that receivers can be "registered" to multiple transmitters (when the same registration id is used). It's marketed as being there so that if you are racing, you have multiple transmitters set up, and if one transmitter goes flat or is faulty, you just pick up another and carry on.

**Comment by pfeerick** [comment]
Still only Frsky radios for the most part - since it is dependent on PXX2 ;)
