### ISSUE TITLE
Images have a  white box

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#485]
Tx16s
Rc4
Model images without back ground is showing a white background. As the image has no background the box should be invisable

**Comment by pfeerick** [comment]
Is this the ModelBMP widget again?

**Comment by Mantamatt1** [comment]
Yes

**Comment by aka13-404** [comment]
As far as I understand, this is now fixed with #878, and will release in 2.6?

**Comment by pfeerick** [comment]
It's actually fixed in main already, and has been for about two weeks now... so present in any of the nightlies. The underlying issue was in the submodule, not the ModelBMP widget, otherwise it would  have indeed been fixed as part of the PR (which was started in order to try and fix that, amongst other things.
