### ISSUE TITLE
Edge TX buddy Froze while erasing firmware

### ISSUE THREAD

**Issue by HeavyJohnny** [EdgeTX/edgetx#4878]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

While updating the firmware on my TX16s Mk2, Edge TX Buddy Froze at 0% erasing Firmware and bricked my TX. I was able to recover it back to the original firmware using STM32CubeProgrammer but am still having the same problem erasing the firmware both with the chrome version of Buddy and the app. Therefore I am unable to update my firmware. Please Help.

### Expected Behavior

I expected my firmware to be upgraded

### Steps To Reproduce

see error

### Version

2.7.1

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

11 pro

**Comment by HeavyJohnny** [comment]
I was able to get it to work after loading 2.8 and then going forward to the latest firmware

**Comment by pfeerick** [comment]
Since you could see the STM32 bootloader, the radio was in DFU mode. Were
you not able to then flash the radio with EdgeTX Buddy? As if you could
flash it with srm32cubeprogrammer, Buddy *should* have been able to flash
it then also.

The version of edgetx running at the time has no bearing on DFU mode - DFU
is built-in functionality of the STM32 MCU.
