### ISSUE TITLE
EdgeTX Companion v2.10.4 - Linux 

### ISSUE THREAD

**Issue by VinceG32** [EdgeTX/edgetx#5583]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

EdgeTX_Companion_2.10.4-x86_64.AppImage
![EdgeTX Linux 2 10 3 and 2 10 4](https://github.com/user-attachments/assets/fee7d2ac-2cef-419e-8671-51ad58e640e4)

### Expected Behavior

New EdgeTX_Companion_2.10.4-x86_64.AppImage Linux crashes. The old version EdgeTX_Companion_2.10.3 starts without error. (Linux Mint 21.2) See attachment. 

### Steps To Reproduce

Test EdgeTX_Companion_2.10.4 on a Linux PC

### Version

2.10.4

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Linux

### OS Version

Linux Mint 21.2

**Comment by pfeerick** [comment]
2.10.4 Companion AppImage is working perfectly for me on Linux Mint. Make sure you have marked the `.AppImage` as executable, and try running it instead of opening it in `xed`. If you had [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) installed on your system and updated to the latest Linux Mint, that does not appear to be compatible with the latest Linux Mint release - hence you need the mark the appimages as executable files so that they run, and they won't automatically integrate into launcher menu.
