### ISSUE TITLE
lcd.sizeText(XXLSIZE) changed it's vertical position on LVGL compared to LCD version

### ISSUE THREAD

**Issue by offer-shmuely** [EdgeTX/edgetx#5608]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

in LVGL the 32px font (XXLSIZE) is placed asymmetrically on the vertical line,

### Expected Behavior

in LVGL the 32px font (XXLSIZE) should be placed symmetrically on the vertical line
the same as non-lvgl version

### Steps To Reproduce

```
local function update(wgt, options)
    wgt.options = options
    lytZone2 = {}
    local text = "FONT XXLSIZE"
    local ts_w1, ts_h1 = lcd.sizeText(text, XXLSIZE)
    lytZone2[#lytZone2+1] = {type="label", text=text, x=10, y=100, font=XXLSIZE, color=WHITE}
    lytZone2[#lytZone2+1] = {type="rectangle", x=10, y=100, w=ts_w1, h=ts_h1, color=BLUE, filled=false}
    lvgl.build(lytZone2)
end

```

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

win11

### Anything else?

![image](https://github.com/user-attachments/assets/fe1fa331-af51-4837-86ed-3eb059d80d55)

**Comment by offer-shmuely** [comment]
![image](https://github.com/user-attachments/assets/7c8e73f1-1d86-49d5-afdd-5c3b22c4f57a)


![image](https://github.com/user-attachments/assets/6e5c46be-ee23-4b22-9f72-f4dfccf40359)

**Comment by philmoz** [comment]
This is because the legacy 'lcd' text drawing function adds an offset when drawing the XL and XXL font characters.
The lvgl text rendering does not add this magic offset.

The comments indicate this was done for compatibility with 2.3.x.

The magic offset is also added to the 'getTextSize()' function for the XL and XXL fonts.

Currently text drawn with XXL looks like this (note the waste space at the top):
![screenshot_t15_24-10-31_22-12-14](https://github.com/user-attachments/assets/e4e8368a-26bf-45bb-b280-a7f1a1707dff)

It should look like this:
![screenshot_t15_24-10-31_22-08-36](https://github.com/user-attachments/assets/7d053642-51b8-4885-bb8a-c5b9cd4fd950)

IMO this magic offset should be removed, although this may change the way some existing scripts look.

**Comment by offer-shmuely** [comment]
since anyone using lvgl is changing code anyway, I see no issue of backward compatibility here, 
So it is better make the textSize as accurate as possible.
