### ISSUE TITLE
[Bug] [NV14] SG & SH interchanged

### ISSUE THREAD

**Issue by LimitlessGreen** [EdgeTX/edgetx#581]
If you try to change SH, the radio is detecting a change in SG and vice versa.
This caught my attention because I was trying to make SG an FM switch (3 states) but the radio was detecting a toggle switch. 

**Describe the bug**
SG & SH interchanged

**Screenshots**
![switches](https://user-images.githubusercontent.com/15064073/128900152-6526b1ca-9801-4d80-9be1-b70aa6f2aaad.jpg)

**General information**
 - EdgeTX version (2.5.0 nightly, f5dec4e31edd8181e6a9925c31a03fa2cb659eef)
 - Hardware (FlySky Nirvana NV14)

---
_Thanks for the nice project :)
-- Limitless Green --_

**Comment by eshifri** [comment]
Yes, this is a new problem - this thing used to work correctly.

Since you are looking at the switches :-), can you please take a look at the list of options, available for logical switches?
I think !SA is missing on NV14.

**Comment by LimitlessGreen** [comment]
This one?

![ls1](https://user-images.githubusercontent.com/15064073/128924232-99dfabce-b1be-4e12-bee4-6998b57b493d.jpg)
![ls2](https://user-images.githubusercontent.com/15064073/128924248-50e3c95e-18c3-441c-9b72-c06b8e3f782b.jpg)

**Comment by eshifri** [comment]
No, sorry I did not make myself clear: if you go to AND switch SA up/down/neutral will be there, but no sign of !SAu, !SAd

**Comment by LimitlessGreen** [comment]
Sorry, I'm a bit new to this stuff. :sweat_smile:
Yes SA is there, but what is !SAu?
I'm assuming an inverted something? :sweat_smile:

**Comment by eshifri** [comment]
Yes :-), inverted SA up or down

**Comment by LimitlessGreen** [comment]
Ahh yes, you're right!
The inverted ones are beginning with !SB
![issue](https://user-images.githubusercontent.com/15064073/128932936-03c6a5fb-cad5-48ee-ade3-e9f3621be0e2.png)

**Comment by eshifri** [comment]
Actually, this is correct: does not make sense for two-position switches.

**Comment by pfeerick** [comment]
It does, and it doesn't... I know myself I was confused at first when I didn't see them on the T-Lite, then realised they were the two position switches, and there are arguments for them to be omitted (since a two position switch is only up or down, there isn't that 'indeterminate' middle position) and for them (because you want to simply say not up, rather than down, well, because). That is why https://github.com/EdgeTX/edgetx/issues/178 is still open for discussion as to whether it should stay as it is or change.

**Comment by raphaelcoeffic** [comment]
Fixed by #584
