### ISSUE TITLE
Custom Scripts don't see Lua outputs name

### ISSUE THREAD

**Issue by BartSoj** [EdgeTX/edgetx#591]
Simple Lua program but the output name doesn't show
![screen](https://user-images.githubusercontent.com/42448881/129445269-2bc4d822-2fca-471f-ae7a-f8f02edd27dc.png)
```
local inputs = {
                 { "Input", SOURCE },
                 { "Percent", VALUE, -100, 100, 5 }
               }

local outputs = { "GtSt" }

local function run(i, p)
  return i*p/100
end

return { input=inputs, output=outputs, run=run }
```

**Comment by raphaelcoeffic** [comment]
@BartSoj could you please state which radio & firmware version you are using?

**Comment by BartSoj** [comment]
I'm using Radiomaster tx16s with Edgetx v2.4.0

**Comment by raphaelcoeffic** [comment]
> I'm using Radiomaster tx16s with Edgetx v2.4.0 ([09a6580](https://github.com/EdgeTX/edgetx/commit/09a65807ecee1b8b4b583b795931f8bc6690d437))

Thx, could you please re-try with latest nightly? I think we had already fixed something like that.

**Comment by BartSoj** [comment]
tried but didn't help

**Comment by pfeerick** [comment]
This is the PR you were thinking off that *should* have fixed this, but it seems to have gone bonkers (sorry, technical term 😆) since... https://github.com/EdgeTX/edgetx/pull/436

TX16S, using the nightly from probably two days ago, adding the mix above as `Mix1.lua`, and the example from the PR as `Mix2.lua`, strange stuff happens. Regardless of which mix I put in the first line, it seems to error... 

![image](https://user-images.githubusercontent.com/5500713/129556076-2ff18214-d8a4-4deb-8164-210e5ded04da.png)
![image](https://user-images.githubusercontent.com/5500713/129556100-34c179e5-ae67-472f-a65f-276fbfcc9083.png)

But you can quite clearly see the second 'instance' of `Mix1` did something... 🤪 

And well, the mixes pages themselves were a bit bare... :-O
![image](https://user-images.githubusercontent.com/5500713/129556218-2fd2c2c8-94c8-44e8-b21a-31082fa69b17.png)
![image](https://user-images.githubusercontent.com/5500713/129556194-a381ab20-87f7-4bbb-8423-a29f7363a0cc.png)

I've never used custom mixes, so could have buggered something up... I just copied the text into a .lua text file, and shoved it into a text file with .lua extension `/SCRIPTS/MIXES` with a less then six character name (hence Mix1, Mix2)... reloaded the model just to be sure... no change. 

As a side issue, the 'Reset' entry in the context menu for the custom scripts page doesn't seem to work.

**Comment by raphaelcoeffic** [comment]
Hmm… seems like the feature needs some attention to keep working 😇

**Comment by pfeerick** [comment]
Is there any chance you could look into this @jfrickmann? It looks like somewhere between 

https://github.com/EdgeTX/edgetx/commit/762ce4ce1fa725b8539eb93a4af4baa36f0a81bf
and 
https://github.com/EdgeTX/edgetx/commit/b0732e156406017e30b6f20cd19dd02034996a62

this broke, and it seems related to the pre-emption PR. `simu`, as well as radio, so that should be of some help. 

The test script I was using was https://raw.githubusercontent.com/RCdiy/OpenTXLua/master/MIXES/GtStd.lua

**Comment by jfrickmann** [comment]
I will look into it

**Comment by jfrickmann** [comment]
I copied the script and fired up the 2.5rc2 simu. It looks fine here - am I missing something?
I used aile and elev as inputs.
![Mix1](https://user-images.githubusercontent.com/16344987/135716789-36c256c8-babd-41be-a956-c6ddd663a7e7.png)
![Mix2](https://user-images.githubusercontent.com/16344987/135716795-a053fe1f-5af2-47aa-9ccb-f46b86fb7469.png)

**Comment by pfeerick** [comment]
Right, so with `cmake -DPCB=X10 -DPCBREV=TX16S -DLUA=Y ..` option (i.e. TX16S, with LUA on for mixer scripts), this is what I get when I add the mixer script linked above on the custom screens page..
![snapshot_02](https://user-images.githubusercontent.com/5500713/135736038-24c5e526-f58a-4aea-ab39-15aa752477c0.png)

and it shows this back at the main screen

![snapshot_01](https://user-images.githubusercontent.com/5500713/135736054-da535a02-06d8-42bf-a607-2b99c5a8e6d6.png)

but if I added it to a second lua line, I get the following

![snapshot_03](https://user-images.githubusercontent.com/5500713/135736073-9e93e346-d19d-481f-82e9-520e4337fe37.png)

However, if I revert back to commit 762ce4c, it is fine. 
![snapshot_04](https://user-images.githubusercontent.com/5500713/135736168-349c47c3-90dd-4ebc-8e52-6bb22e33371d.png)

![snapshot_05](https://user-images.githubusercontent.com/5500713/135736171-9ab148fe-21e4-43b8-88dc-9a0357c7e763.png)

Am I missing something about mixer scripts, or perhaps it's specific to the radio type?

**Comment by jfrickmann** [comment]
I dont know - I was just using TX16S simu from 2.5rc2 Companion. Can you look in the Lua log and see why that error happens?

**Comment by pfeerick** [comment]
Ah ha, well, therein lies the problem... I have now tried with the Companion 2.5 simulator, and that is working fine... so 1) Companion simulator is not reflecting radio hardware behaviour in this instance and 2) Companion simulator is not behaving the same as the same commit `simu`, which does match hardware behaviour. 😱 

This is the log from `simu` [simu_591.txt](https://github.com/EdgeTX/edgetx/files/7272697/simu_591.txt)

And the log from `simulator` from companion [simulator.txt](https://github.com/EdgeTX/edgetx/files/7272698/simulator.txt)

I do see there is a line `-E- : attempt to call a nil value` - but it also appears much earlier on, before the mixer script is even enabled, and will also appear even if the file isn't present. It seemed unrelated, but I also note that message isn't present in the earlier 762ce4c repo state of simu/firmware. [simu_591_oldcommit.txt](https://github.com/EdgeTX/edgetx/files/7272700/simu_591_oldcommit.txt)

Note in all cases I'm doing mostly the same thing - nuking the simulator radio and model settings, starting it afresh, closing it, and then starting again, going to custom scripts tab, picking the mixer script, go out of the page, go back in, no option are shown / options are shown, and then close it all down. I may also try giving the instance a name, but that didn't appear to make any difference.

**Comment by jfrickmann** [comment]
Yeah, the nil value has been there for a while, maybe I should figure out where it comes from 😉 
I will build simulator2_6_ under Linux and see what happens.

**Comment by jfrickmann** [comment]
I just fired up Companion for X9D+, and it does not give me "-E- attempt to call nil value", so that one must be widget related.

**Comment by jfrickmann** [comment]
So I just fired up TX16S under simulator26, freshly built from the current main (0cbb14bc1), and it still works jus fine ...
Now I will grab my radio and see how it looks under 2.5rc2

**Comment by jfrickmann** [comment]
On my TX16S w/ the FW from 2.5rc2 (994c4ff) it errors, but firmware built with the current main head (0cbb14bc1) seems to work just fine. I would say that something is rotten with 2.5rc2, or the build system used for building RCs...
Another thing I noticed, is that it always says 0% on the right side in CUSTOM SCRIPTS - should it give the current value of the first output or something?

**Comment by pfeerick** [comment]
The build system for RCs is the same one that is building every other build - so it isn't that. 

It is possible there is something different with the 2.5rc2 firmware, but 0cbb14b is no different for me when I try the [version from the github build](https://github.com/EdgeTX/edgetx/runs/3779268254) , so I don't know what is going on here. If you are were comparing a self-build 0cbb14b, it sounds like there is something different in your build environment which is letting it work, which is different to both the github actions build, and mine (which is using the same docker container used by the github actions).

**Comment by jfrickmann** [comment]
I just thought of something. The LUA compile flag is a bit odd: YES=Full Lua support incl. mixer scripts; ON=Lua support but no mixer scripts; OFF=no Lua support.
In OTX, the default was ON, and that's why I stopped using it, because I had to explain to my users how to set it to YES and download and install FW again. I bet the same is the case for our standard builds? If that is the case, then we probably build the Mixer script GUI, but there is no support for it under the hood.
So we should probably:
- [ ]  change gui/colorlcd/CmakeLists.txt to only include model_mixer_scripts.cpp for LUA=YES
- [ ] Consider setting the default value -DLUA=YES

I will test it when I get a moment, and let you know what I found, with a PR if it worked.

**Comment by pfeerick** [comment]
I got distracted, so you beat me to this. Yes, that was the problem... and it confused me because the tab was visible...

https://github.com/EdgeTX/edgetx/blob/f970ab1e661fcc90fa2bcb15d35ee323b81621ac/radio/src/gui/colorlcd/menu_model.cpp#L52-L54

This could also be made to test for YES rather than just ON, as it is obviously incorrect atm 🤦 

IMO, it being linked to LUA flag is completely incorrect - it should have had it's own flag, since `LUA` is not `LUA_MIXER_SCRIPT` 🤮

**Comment by jfrickmann** [comment]
In radio/src/CmakeLists.txt:
```
  if(LUA STREQUAL YES)
    add_definitions(-DLUA_MODEL_SCRIPTS)
  endif()
```
So we just need to apply that to compiling and adding the ModelMixerScriptsPage.

**Comment by pfeerick** [comment]
Nice... and then can also forget about LUA=YES, since LUA=ON is generally on by default, and LUA_MODEL_SCRIPTS will probably do the model/mixer scripts whereever it is needed...

**Comment by jfrickmann** [comment]
PR #869 on the way...

**Comment by jfrickmann** [comment]
So I learned the the defines only work in the source code, not in CMakeLists.txt. So I had to use if(LUA STREQUAL YES) in gui/colorlcd/CMakeLists.txt to get the mixer script menu compiled.
