### ISSUE TITLE
Numeric keyboard does not have erase button.

### ISSUE THREAD

**Issue by erwinf** [EdgeTX/edgetx#673]
I just updated to the latest nightly and noticed that when switching to numeric keyboard, there is no backspace option. I had to switch to the abc keyboard to delete incorrectly entered numbers.

Radio: TX16S

**Comment by kevinkoenig** [comment]
That was the original implementation.  It was not modified as part of adding keyboard support.  Should we implement a clear button(), or a backspace.  The issue is like for timers which are numbers with a specific display, backspace might not make sense.

Sent from Mail for Windows

From: erwinf
Sent: Friday, September 3, 2021 10:47 AM
To: EdgeTX/edgetx
Cc: Subscribed
Subject: [EdgeTX/edgetx] Numeric keyboard does not have erase button. (#673)

I just updated to the latest nightly and noticed that when switching to numeric keyboard, there is no backspace option. I had to switch to the abc keyboard to delete incorrectly entered numbers.
Radio: TX16S

**Comment by eshifri** [comment]
I think this is about the keyboard per se - not number_edit.
Actually, there is a backspace there - it is just left at the same place where it was for abc keys.

**Comment by pfeerick** [comment]
NumericEdit, so it's the number keyboard. ;)

I've noticed the DEF/default button seems to go to zero a lot? Maybe that
is sufficient?

**Comment by pfeerick** [comment]
NumericEdit / "when switching to numeric keyboard" ;)

I've noticed the DEF/default button seems to go to zero a lot? Maybe that
is sufficient?

![image](https://user-images.githubusercontent.com/5500713/132077253-2744a5cb-fbe0-49a5-ad68-e85544ef5839.png)

**Comment by eshifri** [comment]
I think it was about full keyboard. The first screen has letters; the second - digits. You cannot delete "22" by switching to "abc" keyboard - no such option. :-)
I think the complaint is e.g. you are editing model name: Edge540. To enter 540 you have to go to the second screen (touch digits button). Delete button is there, but it is at the very bottom - not easy to notice.

**Comment by rotorman** [comment]
@kevinkoenig I just post the info here - we have following remark from a fellow Discord user about the keyboard caps key:
`Hi all, just loaded nightly t18-69efe13 and the keyboard is great my only question so far is the caps arrow is solid in colour when in lower case and not coloured when in upper case which to my way of thinking is reversed as compared to my android mobile phone, not a complaint just an observation:-)`
https://discord.com/channels/839849772864503828/839849772864503832/883579134570266654
Would be sweet if you would have the joy of looking into it. Cheers!

**Comment by MervDale** [comment]
Hmm maybe they should look closer and then ask the question elsewhere first before raising it on GitHub as an issue, just a thought ;-Q

**Comment by pfeerick** [comment]
@eshifri My apologies... I read that too early in the morning before heading out flying... 😆 

Backspace is indeed still there... so 👓 needed 😆 

![image](https://user-images.githubusercontent.com/5500713/132143692-f5dfe825-0e03-4add-b738-0d88798c4dd5.png)
