### ISSUE TITLE
2.6 Themes files structure

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#897]
**SD card folder structure**
/THEMES/ETX/
/THEMES/ETX/theme.yml
/THEMES/ETX/logo.png
/THEMES/ETX/screenshot1.png
/THEMES/ETX/screenshot2.png
/THEMES/ETX/background_320x480.png
/THEMES/ETX/background_480x272.png
/THEMES/ETX/readme.txt

**Description**
ETX - theme name defined by user
theme.yml - theme definition - YAML format
logo.png - theme preview (displayed as first preview) - 480x272 PNG
screenshot1.png - theme preview (optional first screenshot UI with applied theme) - 480x272 PNG
screenshot2.png - theme preview (optional second screenshot UI with applied theme) - 480x272 PNG 
background_320x480.png - theme background file vertical screens (ie NV14) - 320x480 PNG
background_480x272.png - theme background file horizontal screens (is TX16S) - 480x272 PNG
readme.txt - theme information from author

**Implementation Remarks**
9 screenshots allowed - filenames:  screenshot1.png ... screenshot9.png 
Vertical screen radios (NV14) will use horizontal format logo.png & screenshot[1-9].png files to display preview.

**Comment by JimB40** [comment]
to be closed IMHO

**Comment by richardclli** [comment]
The current THEMES do not have subfolders, will this be changed in the future?

**Comment by pfeerick** [comment]
Why closed? Do you think we should not go this way now?

**Comment by kevinkoenig** [comment]
Yes I don’t think we should do it that way anymore.  I have moved the keyboard processing for pg up and dn into a private Page just for the color editor.  I think making this big of a change in the way pg up and down work is not appropriate at this stage.  When we revisit global key binding we can think of what we want for the entire system.  That is my current opinion.  I am willing to be convinced otherwise.

Sent from Mail for Windows

**Comment by pfeerick** [comment]
I think there is some confusion here - this issue is about the structure of themes themselves, not the editor per say. Namely, that there would a folder for each theme, and a standard naming convention for all the files inside. 

So do we:
1) want a folder per theme, i.e. `/THEMES/DVA_Pink/theme.yml`, `/THEMES/RL_Burgundy/theme.yml`, etc
2) flat file structure with all the themes in the one folder `/THEMES/DVA_pink.yml`, `/THEMES/RL_Burgundy.yml`, etc

?

**Comment by JimB40** [comment]
Yes @kevinkoenig it's about data structure for themes on SD card not Theme Editor implementation.
And as always

Why to close? 
1. Because PR went in direction of one folder structure. As we are 3 week prior 'no more features' period for 2.6 I wouldnt't touch fundamental things.
2. There are already themes using this structure. Creating theme repository we created semi-legacy. Not strong but it is.
3. For ETX it does not matter if it is with subfolders or without. It's was for User to minimize risk of overwriting. With Theme Editor dealing with file structure risk is minimized.
4. If flasher will ever evolve into tool we think about. (Help with instalation) risk will be even less. You just browse theme repository and command to 'install' on SD card. Where and how doesn't matter.

**Comment by pfeerick** [comment]
Themes repository is a five second fix with a script that moves each theme group to a folder, and renames the files, so should not be a consideration. 

Being able to copy a folder (as well as make the theme structure more predictable) was one reason I thought the PR would probably go this way, and the sooner we make the change the better. But if you guys think it's too late in the cycle to implement this, that's fine. 

PS: If it was still a possible consideration, could remove 2.6 from the title, and move to 2.7 milestone. Closing basically means not coming back to since it drops off the lists ;)

**Comment by rotorman** [comment]
I would prefer also to change to using a subfolder for each theme, that would make it clearer IMHO. As Peter wrote, changing the existing themes in GitHub, is very easy and quick to do.
If the code could be changed to scan the sub-folders of the SD card \THEMES folder, then this could easily go into 2.6.

**Comment by pfeerick** [comment]
I think we should leave it in the capable hands of @kevinkoenig , since he will have to implement it! If it's an quick and easy change, great please do it! If it's likely to cause blood, tears and lots of swearing... not just yet! 😆

**Comment by JimB40** [comment]
Let @kevinkoenig decide. His time. We should add few more color constants to separate for example topbar background from text that uses same constant. Hope guys wont go to far with external YAML tools for themes as I saw already idea to code such a thing :)

**Comment by kevinkoenig** [comment]
First thanks for asking 😊.  IMHO we should implement this.  I can already see the THEMES folder is messy, and it is difficult to manage the files if you have a lot of themes in there.  Secondly, I have to go into that code anyway because we now have YML support, and I want to rip out my parsing logic.

Here is what I propose:

1. We get what I have now fully checked into main.  That way we know we have something for 2.6.  And since it is already been out there on YouTube…
2. I go in and implement YML support (as per the new libraries)
3. I implement the new file structure, which will be a pretty quick job.

So if we all agree, step 1 is to get the current state checked in and merged into main.  I will work with @pfeerick and get that done ASAP.  I think it is functionally ready.

**Comment by kevinkoenig** [comment]
> I think there is some confusion here - this issue is about the structure of themes themselves, not the editor per say. Namely, that there would a folder for each theme, and a standard naming convention for all the files inside.
> 
> So do we:
> 
> 1. want a folder per theme, i.e. `/THEMES/DVA_Pink/theme.yml`, `/THEMES/RL_Burgundy/theme.yml`, etc
> 2. flat file structure with all the themes in the one folder `/THEMES/DVA_pink.yml`, `/THEMES/RL_Burgundy.yml`, etc
> 
> ?

sorry my bad, I closed a PR in libopenui

**Comment by pfeerick** [comment]
> Here is what I propose:
> 
>     1. We get what I have now fully checked into main.  That way we know we have something for 2.6.  And since it is already been out there on YouTube…
> 
>     2. I go in and implement YML support (as per the new libraries)
> 
>     3. I implement the new file structure, which will be a pretty quick job.

Sounds good to me... :)
