### ISSUE TITLE
EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV on T12 wrong value

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#909]
EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV on T12 have the wrong values (98, 99) instead of (100, 101).

**Comment by pfeerick** [comment]
Since you know the Lua side of things better than me... can you clarify a few things here:
- if you have a name for the event... ie. EVT_VIRTUAL_NEXT, why are you looking at the ID?
- it has the wrong value in reference to what? What makes 100,101 the *right* values?

As my understanding of the events atm is is that because different transmitters / families will expose different events, and the events are basically in a list, that for example... EVT_VIRTUAL_POTATO is not going to be equal to 100 on all radios, not was it expected to be since it was given a name? Or can the name = index relationship not be looked up in code?

**Comment by kasatka60** [comment]
jumper t-lite has the same problem.

**Comment by pfeerick** [comment]
Yeah, I've always had this through that going up and down used the buttons the right way, but increment and decrement were back to front on the t-lite... meaning the buttons are probably mapped back to front.

**Comment by kasatka60** [comment]
How can I change the source code myself to fix it?

**Comment by rotorman** [comment]
You would fork the repository, make a branch and commit your changes there.
For building, see: https://github.com/EdgeTX/edgetx/wiki/Building-and-debugging-EdgeTX
