### ISSUE TITLE
Horus X10 with ISRM upgrade does not work with Edgetx 2.5

### ISSUE THREAD

**Issue by Skippydi** [EdgeTX/edgetx#919]
Hello Edgetx team, 
I have a Horus X10s with ISRM board (upgrade). When flashing with the version x10-accessedgetx-103089808.bin I get the error wrong PCB board.
When flashing with the version x10-edgetx-103089808.bin I have no access selection menu.
When will the EdgeTX version come that works with the ISRM extension version?
 THX

**Comment by raphaelcoeffic** [comment]
This is the wrong firmware. We don‘t builds yet for the isrm upgrade. The one you installed is for the X10 Express.

**Comment by brainbubblersbest** [comment]
I do a build for you, as i currently Do some builds for x10 and x12. Please Tell your needed options.

**Comment by Skippydi** [comment]
Ok, thanks a lot. But what option do I have?

Am So., 21. Nov. 2021 um 12:42 Uhr schrieb brainbubblersbest <
***@***.***>:

**Comment by pfeerick** [comment]
Basically the options in companion, give or take...

![image](https://user-images.githubusercontent.com/5500713/142759820-a06ee327-823e-4efd-b998-70899a8b41a5.png)

**Comment by Skippydi** [comment]
Hi Peter, that’s no problem. I need a possibility to choice Access or D16
for my X10s with ISRM Modul Update. The actually Version works only with
Accst or Access Board

Peter Feerick ***@***.***> schrieb am So. 21. Nov. 2021 um
14:21:

**Comment by raphaelcoeffic** [comment]
#1117 should solve this problem.

**Comment by brainbubblersbest** [comment]
> #1117 should solve this problem.

Whoot. This will solve some Problems. 😍
But I think what he's actually meant is that He will choose between D16 and access on his isrm Module.

**Comment by raphaelcoeffic** [comment]
> > #1117 should solve this problem.
> 
> Whoot. This will solve some Problems. 😍 But I think what he's actually meant is that He will choose between D16 and access on his isrm Module.

Of course, he was using the regular ACCST firmware.

**Comment by brainbubblersbest** [comment]
Anyway. Set the actual used internal Module in edgetx would be a nice thing
to have. 🤗

Raphael Coeffic ***@***.***> schrieb am Mo., 22. Nov. 2021,
06:12:

**Comment by raphaelcoeffic** [comment]
> Anyway. Set the actual used internal Module in edgetx would be a nice thing to have. 🤗

This is exactly what #1117 is doing.

**Comment by Belectone** [comment]
I’m sorry, it’s been a while but I came across this thread and I’m having the same issue. I have a horus X10s with an upgraded Irsm chip and a bunch of RXSR access drones. I can no longer use them if I want to use EdgeTX with the current bin. available I’d like to start using some ELRS modules In newer builds and edge seems a better fit. Do you have a build with noheli, fiachoice, lua, internalacess? I can’t seem to build one on the new companion edgetx the way I did in opentx.

**Comment by pfeerick** [comment]
Lua is enabled by default. Noheli is not needed any more as this can be
chosen at runtime (radio settings => radio => enabled features).
Internalaccess *should* be enabled - you would just need to choose ISRM in
radio settings => hardware settings => internal RF. And I think FAICHOICE
is an option you can pick on buddy under cloud build.

**Comment by Belectone** [comment]
Internalaccess isn’t available. I’ve tried to do the access bin and I get a pcb error. If I I load the x10s bin I only have jxt Sent from my iPhoneOn Aug 16, 2024, at 2:05 PM, Peter Feerick ***@***.***> wrote:﻿
Lua is enabled by default. Noheli is not needed any more as this can be

chosen at runtime (radio settings => radio => enabled features).

Internalaccess *should* be enabled - you would just need to choose ISRM in

radio settings => hardware settings => internal RF. And I think FAICHOICE

is an option you can pick on buddy under cloud build.

**Comment by pfeerick** [comment]
You only have XJT listed here? 
![image](https://github.com/user-attachments/assets/0109ffb4-3a48-4030-b869-b43a88dd67b3)

For a standard release build of X10S for EdgeTX 2.10.1, I'm seeing `internalaccess` listed (screenshot from simulator). 
![image](https://github.com/user-attachments/assets/418d9784-6bd5-4cd0-80c8-fcc3622b90c4)

**Comment by Belectone** [comment]
I have tried a few times and I always get the none isrm option. Notion seeds to want to bind. If I do the access one it will always gives the error. Is there a way of loading a lua like for elrs? I can reload the opentx and it works every time. My x9d runs good but I still have the heli option. I appreciate your l help. Sent from my iPhoneOn Aug 16, 2024, at 11:31 PM, Peter Feerick ***@***.***> wrote:﻿
You only have XJT listed here?
image.png (view on web)
For a standard release build of X10S for EdgeTX 2.10.1, I'm seeing internalaccess listed (screenshot from simulator).
image.png (view on web)

**Comment by pfeerick** [comment]
> I have tried a few times and I always get the none isrm option

You are after ISRM though, aren't you? you did say "upgraded Irsm chip and a bunch of RXSR access drones"... and the R-XSR is both ACCESS and D16 compatible, depending on firmware... (i.e. is it flashed ACCESS or D16, and configured right on the handset correctly as ACCESS or D16?). There is no Lua for ACCESS... everything is configured in firmware, rather than via a third party script. 

What happens when you press the settings button for the module? Does it at least say what the module type is, and _perhaps_ offer settings such as TX power (options offered are module dependent)?

![image](https://github.com/user-attachments/assets/652228de-8d8b-47d4-8703-ffb560ffd07c)

Another check, what is the module status is under radio settings -> version?

![image](https://github.com/user-attachments/assets/fc8b3c93-9738-4b97-8f45-7a32dd4d8d45)
![image](https://github.com/user-attachments/assets/092fe443-959f-4860-b8a6-9bade58616d5)

---

For the heli setting on the X9D+ ... as I mentioned before it is now a "runtime" option, controlled by the "Enabled Features" options... i.e. if you don't want heli page at all, just un-tick it. This option is also available at the model level, and you can turn heli and other tabs/pages on and off at will, on a per model basis. 

> (radio settings/SYS => radio setup => enabled features)

![image](https://github.com/user-attachments/assets/11b21022-753f-4b94-9ec6-a4a6164f73ad)
