### ISSUE TITLE
Make it possible to give model categories different icons and a text label in the top bar

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#956]
When selecting a model the model categories are displayed all the same in the top bar. So these icons are useless since there is no way to directly selecting the right categorie, one has to iterate over them to see the name of the categorie.

I would be best to have the possibiliyt to define custom icons for each category.

At least there should be the name of the category in the top bar.

**Comment by JimB40** [comment]
Just preliminary layout with leftside area intended for labels
![Screenshot 2021-11-11 at 05 44 58](https://user-images.githubusercontent.com/46420768/141238723-f0b3565f-53ff-4328-96ad-51f9ec139149.png)
Due to nature of labels they should be text-based rather than icons. Maybe with exception for "Favourite" label where star ot heart serves well in many UI implementations
